// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_account_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_account_registry
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-account-registry/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_account_registry`.
pub trait WeightInfo {
	fn register_account() -> Weight;
	fn deregister_account() -> Weight;
	fn anchor_nonce() -> Weight;
}

/// Weights for `pallet_x3_account_registry` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3AccountRegistry::AccountRegistry` (r:1 w:1)
	/// Proof: `X3AccountRegistry::AccountRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AtlasRegistry` (r:1 w:1)
	/// Proof: `X3AccountRegistry::AtlasRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AccountCount` (r:1 w:1)
	/// Proof: `X3AccountRegistry::AccountCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AccountKinds` (r:0 w:1)
	/// Proof: `X3AccountRegistry::AccountKinds` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn register_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `3545`
		// Minimum execution time: 50_980_000 picoseconds.
		Weight::from_parts(52_061_000, 3545)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `X3AccountRegistry::AccountRegistry` (r:1 w:1)
	/// Proof: `X3AccountRegistry::AccountRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AccountCount` (r:1 w:1)
	/// Proof: `X3AccountRegistry::AccountCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AtlasRegistry` (r:0 w:1)
	/// Proof: `X3AccountRegistry::AtlasRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AccountKinds` (r:0 w:1)
	/// Proof: `X3AccountRegistry::AccountKinds` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn deregister_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `284`
		//  Estimated: `3545`
		// Minimum execution time: 51_155_000 picoseconds.
		Weight::from_parts(51_799_000, 3545)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `X3AccountRegistry::AccountRegistry` (r:1 w:0)
	/// Proof: `X3AccountRegistry::AccountRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::CrossVmNonces` (r:1 w:0)
	/// Proof: `X3AccountRegistry::CrossVmNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn anchor_nonce() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `253`
		//  Estimated: `3545`
		// Minimum execution time: 39_239_000 picoseconds.
		Weight::from_parts(40_156_000, 3545)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3AccountRegistry::AccountRegistry` (r:1 w:1)
	/// Proof: `X3AccountRegistry::AccountRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AtlasRegistry` (r:1 w:1)
	/// Proof: `X3AccountRegistry::AtlasRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AccountCount` (r:1 w:1)
	/// Proof: `X3AccountRegistry::AccountCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AccountKinds` (r:0 w:1)
	/// Proof: `X3AccountRegistry::AccountKinds` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn register_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `3545`
		// Minimum execution time: 50_980_000 picoseconds.
		Weight::from_parts(52_061_000, 3545)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `X3AccountRegistry::AccountRegistry` (r:1 w:1)
	/// Proof: `X3AccountRegistry::AccountRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AccountCount` (r:1 w:1)
	/// Proof: `X3AccountRegistry::AccountCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AtlasRegistry` (r:0 w:1)
	/// Proof: `X3AccountRegistry::AtlasRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::AccountKinds` (r:0 w:1)
	/// Proof: `X3AccountRegistry::AccountKinds` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn deregister_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `284`
		//  Estimated: `3545`
		// Minimum execution time: 51_155_000 picoseconds.
		Weight::from_parts(51_799_000, 3545)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `X3AccountRegistry::AccountRegistry` (r:1 w:0)
	/// Proof: `X3AccountRegistry::AccountRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3AccountRegistry::CrossVmNonces` (r:1 w:0)
	/// Proof: `X3AccountRegistry::CrossVmNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn anchor_nonce() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `253`
		//  Estimated: `3545`
		// Minimum execution time: 39_239_000 picoseconds.
		Weight::from_parts(40_156_000, 3545)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
}
