#![deny(unsafe_code)]
#![cfg_attr(not(feature = "std"), no_std)]
#![allow(deprecated)]
#![allow(missing_docs)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::let_unit_value)]
#![allow(clippy::must_use_candidate)]
#![allow(clippy::cast_possible_truncation)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::if_not_else)]
#![allow(clippy::empty_line_after_outer_attr)]
#![allow(clippy::redundant_closure_for_method_calls)]
#![allow(clippy::map_unwrap_or)]
#![allow(clippy::multiple_bound_locations)]

pub use pallet::*;

// Generated by `./target/release/x3-chain-node benchmark pallet`. Every
// dispatchable charges its measured weight instead of the 5,000-15,000 literals
// it used to.
pub mod weights;
pub use weights::WeightInfo;

#[cfg(feature = "runtime-benchmarks")]
pub mod benchmarking;

#[cfg(test)]
mod mock;

#[cfg(test)]
mod tests;

#[frame_support::pallet]
pub mod pallet {
    use crate::weights::WeightInfo;
    use frame_support::pallet_prelude::*;
    use frame_system::ensure_root;
    use frame_system::pallet_prelude::*;
    use sp_runtime::traits::{Hash, SaturatedConversion};
    use sp_std::vec::Vec;
    use x3_wallet::{
        biometric_unlock::BiometricManager, social_recovery::SocialRecoveryManager, AddressBook,
        BiometricProfile, GuardianAccount, HardwareWallet, MultisigWallet, RecoveryRequest,
        TransactionApproval, UnlockSession,
    };

    /// Max wallets per account
    pub const MAX_WALLETS_PER_ACCOUNT: u32 = 10;
    /// Max multisig signers
    pub const MAX_MULTISIG_SIGNERS: u32 = 50;
    /// Max contacts in address book
    pub const MAX_CONTACTS: u32 = 1000;

    #[pallet::config]
    pub trait Config: frame_system::Config {
        /// Measured weights, generated by the FRAME benchmark CLI.
        type WeightInfo: WeightInfo;
    }

    #[pallet::pallet]
    #[pallet::without_storage_info]
    pub struct Pallet<T>(_);

    /// Store hardware wallets per account
    #[pallet::storage]
    pub type HardwareWallets<T: Config> =
        StorageMap<_, Blake2_128Concat, (T::AccountId, [u8; 32]), HardwareWallet, OptionQuery>;

    /// Store multisig wallets per account
    #[pallet::storage]
    pub type MultisigWallets<T: Config> =
        StorageMap<_, Blake2_128Concat, (T::AccountId, [u8; 32]), MultisigWallet, OptionQuery>;

    /// Store social recovery accounts per user
    #[pallet::storage]
    pub type RecoveryAccounts<T: Config> =
        StorageMap<_, Blake2_128Concat, T::AccountId, GuardianAccount, OptionQuery>;

    /// Store token balances
    #[pallet::storage]
    pub type TokenBalances<T: Config> = StorageMap<
        _,
        Blake2_128Concat,
        (T::AccountId, [u8; 32]),
        u128, // balance
        ValueQuery,
    >;

    /// Store transaction approvals
    #[pallet::storage]
    pub type TransactionApprovals<T: Config> =
        StorageMap<_, Blake2_128Concat, [u8; 32], TransactionApproval, OptionQuery>;

    /// Store address books per account
    #[pallet::storage]
    pub type AddressBooks<T: Config> =
        StorageMap<_, Blake2_128Concat, T::AccountId, AddressBook, OptionQuery>;

    /// Store biometric profiles
    #[pallet::storage]
    pub type BiometricProfiles<T: Config> =
        StorageMap<_, Blake2_128Concat, T::AccountId, BiometricProfile, OptionQuery>;

    /// Store unlock sessions
    #[pallet::storage]
    pub type UnlockSessions<T: Config> =
        StorageMap<_, Blake2_128Concat, [u8; 32], UnlockSession, OptionQuery>;

    /// S1-3: Authorized minters for token operations
    #[pallet::storage]
    pub type Minters<T: Config> = StorageMap<_, Blake2_128Concat, T::AccountId, (), OptionQuery>;

    /// A pending or executed social-recovery request, per account.
    ///
    /// `initiate_recovery` used to take a caller-supplied `new_owner` and *only emit an event* —
    /// no guardians, no quorum, no delay, no state change (measured 2026-09-26; the event read
    /// like a completed hand-over). The request now lives here and is only produced through
    /// `SocialRecoveryManager`, which requires an active guardian set and a delay.
    #[pallet::storage]
    pub type RecoveryRequests<T: Config> =
        StorageMap<_, Blake2_128Concat, T::AccountId, RecoveryRequest, OptionQuery>;

    #[pallet::event]
    #[pallet::generate_deposit(pub(super) fn deposit_event)]
    pub enum Event<T: Config> {
        /// Hardware wallet connected
        HardwareWalletConnected {
            account: T::AccountId,
            device_type: u8,
        },
        /// Multisig wallet created
        MultisigWalletCreated {
            account: T::AccountId,
            threshold: u32,
        },
        /// Social recovery initiated
        RecoveryInitiated {
            account: T::AccountId,
            request_id: [u8; 32],
            new_owner: [u8; 32],
            executable_block: u64,
        },
        /// A guardian set was registered for an account
        RecoveryGuardiansRegistered {
            account: T::AccountId,
            guardians: u32,
            required: u32,
            delay_blocks: u64,
        },
        /// A guardian approved a pending recovery
        RecoveryApproved {
            account: T::AccountId,
            guardian: [u8; 32],
            approvals: u32,
            required: u32,
        },
        /// A recovery completed: the account's recovery owner changed
        RecoveryExecuted {
            account: T::AccountId,
            previous_owner: [u8; 32],
            new_owner: [u8; 32],
        },
        /// The recovery owner cancelled a pending request
        RecoveryCancelled {
            account: T::AccountId,
            request_id: [u8; 32],
        },
        /// Transaction approval requested
        ApprovalRequested { account: T::AccountId, amount: u128 },
        /// Token balance updated
        BalanceUpdated {
            account: T::AccountId,
            token_id: [u8; 32],
            amount: u128,
        },
        /// Biometric profile created
        BiometricProfileCreated { account: T::AccountId },
        /// Unlock session created
        UnlockSessionCreated { account: T::AccountId },
    }

    #[pallet::error]
    pub enum Error<T> {
        /// Wallet not found
        WalletNotFound,
        /// Unauthorized
        Unauthorized,
        /// Invalid amount
        InvalidAmount,
        /// Balance too low
        InsufficientBalance,
        /// Multisig threshold error
        InvalidThreshold,
        /// Too many wallets
        TooManyWallets,
        /// Recovery not approved
        RecoveryNotApproved,
        /// Biometric type is not one this chain accepts (0=fingerprint, 1=face, 2=iris)
        InvalidBiometricType,
        /// The biometric template hash is empty
        EmptyTemplateHash,
        /// The PIN hash is empty, so the profile would have no fallback
        EmptyPinHash,
        /// The biometric profile was refused for a reason without its own variant
        InvalidBiometricProfile,
        /// The guardian set is empty, too large, or the threshold cannot be met
        InvalidGuardianSet,
        /// This account already has a registered guardian set
        RecoveryAccountExists,
        /// The caller is not a guardian of this account
        NotGuardian,
        /// The caller does not own this account's recovery record
        NotRecoveryOwner,
        /// A recovery request is already pending for this account
        RecoveryAlreadyPending,
        /// No recovery request exists for this account
        NoRecoveryRequest,
        /// The request has not reached its threshold, or its delay has not elapsed
        RecoveryNotReady,
        /// This guardian has already approved this request
        DuplicateGuardianApproval,
        /// The account's guardian set is marked inactive
        RecoveryInactive,
    }

    #[pallet::call]
    impl<T: Config> Pallet<T> {
        /// Register a new hardware wallet
        #[pallet::call_index(0)]
        #[pallet::weight(T::WeightInfo::register_hardware_wallet())]
        pub fn register_hardware_wallet(
            origin: OriginFor<T>,
            device_type: u8,
            device_model: Vec<u8>,
            public_key: [u8; 32],
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;
            let wallet_id = T::Hashing::hash_of(&public_key).encode();
            let mut wallet_id_array = [0u8; 32];
            wallet_id_array.copy_from_slice(&wallet_id[..32.min(wallet_id.len())]);

            let hardware_wallet = HardwareWallet {
                id: wallet_id_array,
                device_type,
                device_model: device_model.clone(),
                derivation_path: Vec::new(),
                public_key: public_key.to_vec(),
                address: [0u8; 32],
                is_connected: true,
                last_connected_block: frame_system::Pallet::<T>::block_number()
                    .saturated_into::<u64>(),
                transaction_count: 0,
                firmware_version: Vec::new(),
            };

            HardwareWallets::<T>::insert((who.clone(), wallet_id_array), hardware_wallet);
            Self::deposit_event(Event::HardwareWalletConnected {
                account: who,
                device_type,
            });

            Ok(())
        }

        /// Create a multisig wallet
        #[pallet::call_index(1)]
        #[pallet::weight(T::WeightInfo::create_multisig_wallet())]
        pub fn create_multisig_wallet(
            origin: OriginFor<T>,
            signers: Vec<[u8; 32]>,
            threshold: u32,
            timelock_delay: u64,
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;

            ensure!(
                threshold > 0 && threshold as usize <= signers.len(),
                Error::<T>::InvalidThreshold
            );

            let mut wallet_id = [0u8; 32];
            let encoded = who.encode();
            let copy_len = encoded.len().min(32);
            wallet_id[..copy_len].copy_from_slice(&encoded[..copy_len]);

            let multisig = MultisigWallet {
                id: wallet_id,
                signers: signers.to_vec(),
                threshold,
                owner: [0u8; 32],
                created_block: frame_system::Pallet::<T>::block_number().saturated_into::<u64>(),
                timelock_delay,
                is_active: true,
            };

            MultisigWallets::<T>::insert((who.clone(), wallet_id), multisig);
            Self::deposit_event(Event::MultisigWalletCreated {
                account: who,
                threshold,
            });

            Ok(())
        }

        /// Transfer tokens (with approval checks)
        #[pallet::call_index(2)]
        #[pallet::weight(T::WeightInfo::transfer_tokens())]
        pub fn transfer_tokens(
            origin: OriginFor<T>,
            token_id: [u8; 32],
            to: T::AccountId,
            amount: u128,
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;

            ensure!(amount > 0, Error::<T>::InvalidAmount);

            let current_balance = TokenBalances::<T>::get((who.clone(), token_id));
            ensure!(current_balance >= amount, Error::<T>::InsufficientBalance);

            let new_balance = current_balance - amount;
            TokenBalances::<T>::insert((who.clone(), token_id), new_balance);

            let to_balance = TokenBalances::<T>::get((to.clone(), token_id));
            TokenBalances::<T>::insert((to.clone(), token_id), to_balance + amount);

            Self::deposit_event(Event::BalanceUpdated {
                account: who,
                token_id,
                amount: new_balance,
            });

            Ok(())
        }

        /// Register biometric profile
        ///
        /// The profile is built by `BiometricManager::create_profile`, not by hand. Measured
        /// 2026-09-26: this extrinsic used to store whatever it was given — `biometric_type` of any
        /// value, an all-zero template hash, an all-zero PIN hash — and hardcoded
        /// `owner: [0u8; 32]`, so the stored profile did not name the account that registered it.
        /// The checks existed in `crates/x3-wallet` the whole time; the pallet just did not call
        /// them.
        #[pallet::call_index(3)]
        #[pallet::weight(T::WeightInfo::register_biometric())]
        pub fn register_biometric(
            origin: OriginFor<T>,
            biometric_type: u8,
            template_hash: [u8; 32],
            pin_hash: [u8; 32],
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;
            let now = frame_system::Pallet::<T>::block_number().saturated_into::<u64>();

            let profile = BiometricManager::create_profile(
                Self::account_bytes(&who),
                biometric_type,
                template_hash,
                pin_hash,
                now,
            )
            .map_err(|reason| match reason {
                "Invalid biometric type" => Error::<T>::InvalidBiometricType,
                "Invalid template hash" => Error::<T>::EmptyTemplateHash,
                "PIN hash required" => Error::<T>::EmptyPinHash,
                // Anything this pallet has not been taught to name is still refused, and the
                // mapping test below pins the messages above so a library rename cannot silently
                // turn a specific refusal into the generic one.
                _ => Error::<T>::InvalidBiometricProfile,
            })?;

            BiometricProfiles::<T>::insert(who.clone(), profile);
            Self::deposit_event(Event::BiometricProfileCreated { account: who });

            Ok(())
        }

        /// Register the guardians that may recover this account.
        ///
        /// Owner-only. The set is built by `SocialRecoveryManager::create_recovery_account`, which
        /// is where the "at least one guardian, a threshold the set can meet, at most 30 guardians"
        /// rules live; the pallet previously had no path that created a `GuardianAccount` at all,
        /// which is why its recovery tests had to insert one into storage by hand.
        #[pallet::call_index(8)]
        #[pallet::weight(T::WeightInfo::register_recovery_guardians())]
        pub fn register_recovery_guardians(
            origin: OriginFor<T>,
            guardians: Vec<[u8; 32]>,
            required_guardians: u32,
            recovery_delay_blocks: u64,
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;
            ensure!(
                !RecoveryAccounts::<T>::contains_key(&who),
                Error::<T>::RecoveryAccountExists
            );

            let account = SocialRecoveryManager::create_recovery_account(
                Self::account_bytes(&who),
                guardians,
                required_guardians,
                recovery_delay_blocks,
            )
            .map_err(|_| Error::<T>::InvalidGuardianSet)?;

            let guardian_count = account.guardians.len() as u32;
            RecoveryAccounts::<T>::insert(
                who.clone(),
                GuardianAccount {
                    // The library derives its id from the owner's first 16 bytes; keeping the
                    // record's own `owner` field authoritative is what makes the finalize below
                    // observable.
                    owner: account.owner,
                    ..account
                },
            );

            Self::deposit_event(Event::RecoveryGuardiansRegistered {
                account: who,
                guardians: guardian_count,
                required: required_guardians,
                delay_blocks: recovery_delay_blocks,
            });

            Ok(())
        }

        /// A guardian starts recovery of `account_id`.
        ///
        /// Guardian-only, and a request is only created from an active guardian set (the library
        /// refuses an inactive one, a `new_owner` equal to the current owner, and a set the
        /// threshold cannot satisfy). The request carries the delay: nothing changes ownership
        /// until `finalize_recovery`, after the threshold is met *and* the delay has passed.
        ///
        /// `account_id` is named explicitly because the caller is a *guardian*: keying the request
        /// off the caller (which is what the first version of this change did) looks up the wrong
        /// record. The original extrinsic took no account at all, which is part of why it could
        /// only ever announce a `new_owner` for whoever called it.
        #[pallet::call_index(4)]
        #[pallet::weight(T::WeightInfo::initiate_recovery())]
        pub fn initiate_recovery(
            origin: OriginFor<T>,
            account_id: T::AccountId,
            new_owner: [u8; 32],
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;
            let caller = Self::account_bytes(&who);

            let account =
                RecoveryAccounts::<T>::get(account_id.clone()).ok_or(Error::<T>::WalletNotFound)?;
            ensure!(account.guardians.contains(&caller), Error::<T>::NotGuardian);
            ensure!(
                !RecoveryRequests::<T>::contains_key(&account_id),
                Error::<T>::RecoveryAlreadyPending
            );

            let now = frame_system::Pallet::<T>::block_number().saturated_into::<u64>();
            let request = SocialRecoveryManager::initiate_recovery(&account, new_owner, now)
                .map_err(|_| Error::<T>::RecoveryNotReady)?;

            RecoveryRequests::<T>::insert(account_id.clone(), request.clone());
            Self::deposit_event(Event::RecoveryInitiated {
                account: account_id,
                request_id: request.id,
                new_owner,
                executable_block: request.executable_block,
            });

            Ok(())
        }

        /// A guardian approves the pending recovery request for an account.
        ///
        /// The library refuses a duplicate approval, an inactive set, and a request that is no
        /// longer pending, so an approval cannot be counted twice.
        #[pallet::call_index(9)]
        #[pallet::weight(T::WeightInfo::approve_recovery())]
        pub fn approve_recovery(origin: OriginFor<T>, account: T::AccountId) -> DispatchResult {
            let who = ensure_signed(origin)?;
            let guardian = Self::account_bytes(&who);

            let guardians =
                RecoveryAccounts::<T>::get(account.clone()).ok_or(Error::<T>::WalletNotFound)?;
            ensure!(
                guardians.guardians.contains(&guardian),
                Error::<T>::NotGuardian
            );

            let mut request =
                RecoveryRequests::<T>::get(account.clone()).ok_or(Error::<T>::NoRecoveryRequest)?;
            let now = frame_system::Pallet::<T>::block_number().saturated_into::<u64>();

            SocialRecoveryManager::guardian_approve_recovery(
                &guardians,
                &mut request,
                guardian,
                [0u8; 32],
                now,
            )
            .map_err(|reason| match reason {
                "Not an authorized guardian" => Error::<T>::NotGuardian,
                "Guardian already approved" => Error::<T>::DuplicateGuardianApproval,
                "Account not active" => Error::<T>::RecoveryInactive,
                // "Recovery not pending" and anything unnamed: there is nothing to approve.
                _ => Error::<T>::NoRecoveryRequest,
            })?;

            let approvals = request.approvals.len() as u32;
            RecoveryRequests::<T>::insert(account.clone(), request);
            Self::deposit_event(Event::RecoveryApproved {
                account,
                guardian,
                approvals,
                required: guardians.required_guardians,
            });

            Ok(())
        }

        /// Finalize a recovery once its threshold is met and its delay has elapsed.
        ///
        /// This is the only place the account's recovery owner changes. Both conditions are checked
        /// before any write — the library's `is_recovery_approved` and `can_execute_recovery` — and
        /// the request is marked executed so it cannot be finalized twice.
        #[pallet::call_index(10)]
        #[pallet::weight(T::WeightInfo::finalize_recovery())]
        pub fn finalize_recovery(origin: OriginFor<T>, account: T::AccountId) -> DispatchResult {
            let who = ensure_signed(origin)?;
            let caller = Self::account_bytes(&who);

            let mut guardians =
                RecoveryAccounts::<T>::get(account.clone()).ok_or(Error::<T>::WalletNotFound)?;
            ensure!(
                guardians.guardians.contains(&caller),
                Error::<T>::NotGuardian
            );

            let mut request =
                RecoveryRequests::<T>::get(account.clone()).ok_or(Error::<T>::NoRecoveryRequest)?;
            let now = frame_system::Pallet::<T>::block_number().saturated_into::<u64>();

            ensure!(
                SocialRecoveryManager::is_recovery_approved(&guardians, &request),
                Error::<T>::RecoveryNotApproved
            );
            ensure!(
                SocialRecoveryManager::can_execute_recovery(&request, now)
                    .map_err(|_| Error::<T>::RecoveryNotApproved)?,
                Error::<T>::RecoveryNotReady
            );

            // Captured before the execution moves the owner, so the event reports the change
            // rather than repeating the new owner in both fields (measured: the first version of
            // this reported `previous_owner == new_owner`).
            let previous_owner = guardians.owner;
            SocialRecoveryManager::execute_recovery(&mut guardians, &mut request, now)
                .map_err(|_| Error::<T>::RecoveryNotReady)?;

            // The one write that makes this a recovery and not an announcement.
            RecoveryAccounts::<T>::insert(
                account.clone(),
                GuardianAccount {
                    owner: request.new_owner,
                    ..guardians
                },
            );
            RecoveryRequests::<T>::insert(account.clone(), request.clone());

            Self::deposit_event(Event::RecoveryExecuted {
                account,
                previous_owner,
                new_owner: request.new_owner,
            });

            Ok(())
        }

        /// The account's recovery owner cancels a pending request.
        #[pallet::call_index(11)]
        #[pallet::weight(T::WeightInfo::cancel_recovery())]
        pub fn cancel_recovery(origin: OriginFor<T>, account: T::AccountId) -> DispatchResult {
            let who = ensure_signed(origin)?;
            let caller = Self::account_bytes(&who);

            let guardians =
                RecoveryAccounts::<T>::get(account.clone()).ok_or(Error::<T>::WalletNotFound)?;
            ensure!(caller == guardians.owner, Error::<T>::NotRecoveryOwner);

            let mut request =
                RecoveryRequests::<T>::get(account.clone()).ok_or(Error::<T>::NoRecoveryRequest)?;
            SocialRecoveryManager::cancel_recovery(&mut request, caller, guardians.owner)
                .map_err(|_| Error::<T>::NoRecoveryRequest)?;

            RecoveryRequests::<T>::remove(&account);
            Self::deposit_event(Event::RecoveryCancelled {
                account,
                request_id: request.id,
            });

            Ok(())
        }

        /// Mint tokens (root / governance only).
        ///
        /// S1-3 fix: previous implementation only required `ensure_signed`
        /// and used unchecked addition, which allowed any signed account to
        /// inflate balances arbitrarily and trigger overflows. Mint authority
        /// is now restricted to the root origin (governance / sudo) and the
        /// balance update uses `checked_add` to reject overflow.
        #[pallet::call_index(5)]
        #[pallet::weight(T::WeightInfo::mint_tokens())]
        pub fn mint_tokens(
            origin: OriginFor<T>,
            token_id: [u8; 32],
            to: T::AccountId,
            amount: u128,
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;
            // S1-3: only authorized minters may mint.
            Self::ensure_minter(&who)?;
            ensure!(amount > 0, Error::<T>::InvalidAmount);

            let current = TokenBalances::<T>::get((to.clone(), token_id));
            let new_balance = current
                .checked_add(amount)
                .ok_or(Error::<T>::InvalidAmount)?;
            TokenBalances::<T>::insert((to.clone(), token_id), new_balance);

            Self::deposit_event(Event::BalanceUpdated {
                account: to,
                token_id,
                amount: new_balance,
            });

            Ok(())
        }

        /// S1-3: Add authorized minter
        #[pallet::call_index(6)]
        #[pallet::weight(T::WeightInfo::add_minter())]
        pub fn add_minter(origin: OriginFor<T>, who: T::AccountId) -> DispatchResult {
            ensure_root(origin)?;
            Minters::<T>::insert(&who, ());
            Ok(())
        }

        /// S1-3: Remove authorized minter
        #[pallet::call_index(7)]
        #[pallet::weight(T::WeightInfo::remove_minter())]
        pub fn remove_minter(origin: OriginFor<T>, who: T::AccountId) -> DispatchResult {
            ensure_root(origin)?;
            Minters::<T>::remove(&who);
            Ok(())
        }
    }

    // Internal helpers (not dispatchable)
    impl<T: Config> Pallet<T> {
        /// S1-3: Ensure caller is authorized minter
        fn ensure_minter(who: &T::AccountId) -> Result<(), Error<T>> {
            ensure!(Minters::<T>::contains_key(who), Error::<T>::Unauthorized);
            Ok(())
        }
    }

    // RPC query methods
    impl<T: Config> Pallet<T> {
        /// Get hardware wallet by ID
        pub fn get_hardware_wallet(
            account: &T::AccountId,
            wallet_id: &[u8; 32],
        ) -> Option<HardwareWallet> {
            HardwareWallets::<T>::get((account.clone(), *wallet_id))
        }

        /// Get multisig wallet
        pub fn get_multisig_wallet(
            account: &T::AccountId,
            wallet_id: &[u8; 32],
        ) -> Option<MultisigWallet> {
            MultisigWallets::<T>::get((account.clone(), *wallet_id))
        }

        /// Get token balance
        pub fn get_token_balance(account: &T::AccountId, token_id: &[u8; 32]) -> u128 {
            TokenBalances::<T>::get((account.clone(), *token_id))
        }

        /// Get biometric profile
        pub fn get_biometric_profile(account: &T::AccountId) -> Option<BiometricProfile> {
            BiometricProfiles::<T>::get(account)
        }

        /// Get recovery account
        pub fn get_recovery_account(account: &T::AccountId) -> Option<GuardianAccount> {
            RecoveryAccounts::<T>::get(account)
        }

        /// This pallet's 32-byte identity for an account, used by the `x3-wallet` managers, whose
        /// types carry `[u8; 32]` addresses rather than `T::AccountId`.
        ///
        /// Same convention as `create_multisig_wallet` (the encoded account, truncated to 32
        /// bytes) so a guardian id and a wallet id mean the same thing on this chain.
        pub fn account_bytes(account: &T::AccountId) -> [u8; 32] {
            let mut out = [0u8; 32];
            let encoded = account.encode();
            let copy_len = encoded.len().min(32);
            out[..copy_len].copy_from_slice(&encoded[..copy_len]);
            out
        }

        /// The pending recovery request for an account, if any.
        pub fn get_recovery_request(account: &T::AccountId) -> Option<RecoveryRequest> {
            RecoveryRequests::<T>::get(account)
        }
    }
}
