// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_wallet_pallet`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_wallet_pallet
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-wallet-pallet/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_wallet_pallet`.
pub trait WeightInfo {
	fn register_hardware_wallet() -> Weight;
	fn create_multisig_wallet() -> Weight;
	fn transfer_tokens() -> Weight;
	fn register_biometric() -> Weight;
	fn register_recovery_guardians() -> Weight;
	fn initiate_recovery() -> Weight;
	fn approve_recovery() -> Weight;
	fn finalize_recovery() -> Weight;
	fn cancel_recovery() -> Weight;
	fn mint_tokens() -> Weight;
	fn add_minter() -> Weight;
	fn remove_minter() -> Weight;
}

/// Weights for `pallet_x3_wallet_pallet` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3WalletPallet::HardwareWallets` (r:0 w:1)
	/// Proof: `X3WalletPallet::HardwareWallets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_hardware_wallet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 28_639_000 picoseconds.
		Weight::from_parts(31_154_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::MultisigWallets` (r:0 w:1)
	/// Proof: `X3WalletPallet::MultisigWallets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_multisig_wallet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 26_581_000 picoseconds.
		Weight::from_parts(28_325_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::TokenBalances` (r:2 w:2)
	/// Proof: `X3WalletPallet::TokenBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transfer_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `232`
		//  Estimated: `6172`
		// Minimum execution time: 44_186_000 picoseconds.
		Weight::from_parts(50_592_000, 6172)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3WalletPallet::BiometricProfiles` (r:0 w:1)
	/// Proof: `X3WalletPallet::BiometricProfiles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_biometric() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 25_624_000 picoseconds.
		Weight::from_parts(29_404_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::RecoveryAccounts` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_recovery_guardians() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3541`
		// Minimum execution time: 34_217_000 picoseconds.
		Weight::from_parts(37_647_000, 3541)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::RecoveryAccounts` (r:1 w:0)
	/// Proof: `X3WalletPallet::RecoveryAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3WalletPallet::RecoveryRequests` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn initiate_recovery() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `263`
		//  Estimated: `3728`
		// Minimum execution time: 44_626_000 picoseconds.
		Weight::from_parts(45_405_000, 3728)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::RecoveryAccounts` (r:1 w:0)
	/// Proof: `X3WalletPallet::RecoveryAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3WalletPallet::RecoveryRequests` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_recovery() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `450`
		//  Estimated: `3915`
		// Minimum execution time: 48_064_000 picoseconds.
		Weight::from_parts(52_101_000, 3915)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::RecoveryAccounts` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3WalletPallet::RecoveryRequests` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn finalize_recovery() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `482`
		//  Estimated: `3947`
		// Minimum execution time: 52_235_000 picoseconds.
		Weight::from_parts(53_638_000, 3947)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3WalletPallet::RecoveryAccounts` (r:1 w:0)
	/// Proof: `X3WalletPallet::RecoveryAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3WalletPallet::RecoveryRequests` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_recovery() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `450`
		//  Estimated: `3915`
		// Minimum execution time: 45_685_000 picoseconds.
		Weight::from_parts(46_760_000, 3915)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::Minters` (r:1 w:0)
	/// Proof: `X3WalletPallet::Minters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3WalletPallet::TokenBalances` (r:1 w:1)
	/// Proof: `X3WalletPallet::TokenBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn mint_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `150`
		//  Estimated: `3615`
		// Minimum execution time: 39_750_000 picoseconds.
		Weight::from_parts(40_754_000, 3615)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::Minters` (r:0 w:1)
	/// Proof: `X3WalletPallet::Minters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_minter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 14_291_000 picoseconds.
		Weight::from_parts(16_086_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::Minters` (r:0 w:1)
	/// Proof: `X3WalletPallet::Minters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_minter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 13_502_000 picoseconds.
		Weight::from_parts(14_309_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3WalletPallet::HardwareWallets` (r:0 w:1)
	/// Proof: `X3WalletPallet::HardwareWallets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_hardware_wallet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 28_639_000 picoseconds.
		Weight::from_parts(31_154_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::MultisigWallets` (r:0 w:1)
	/// Proof: `X3WalletPallet::MultisigWallets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_multisig_wallet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 26_581_000 picoseconds.
		Weight::from_parts(28_325_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::TokenBalances` (r:2 w:2)
	/// Proof: `X3WalletPallet::TokenBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transfer_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `232`
		//  Estimated: `6172`
		// Minimum execution time: 44_186_000 picoseconds.
		Weight::from_parts(50_592_000, 6172)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3WalletPallet::BiometricProfiles` (r:0 w:1)
	/// Proof: `X3WalletPallet::BiometricProfiles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_biometric() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 25_624_000 picoseconds.
		Weight::from_parts(29_404_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::RecoveryAccounts` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_recovery_guardians() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3541`
		// Minimum execution time: 34_217_000 picoseconds.
		Weight::from_parts(37_647_000, 3541)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::RecoveryAccounts` (r:1 w:0)
	/// Proof: `X3WalletPallet::RecoveryAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3WalletPallet::RecoveryRequests` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn initiate_recovery() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `263`
		//  Estimated: `3728`
		// Minimum execution time: 44_626_000 picoseconds.
		Weight::from_parts(45_405_000, 3728)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::RecoveryAccounts` (r:1 w:0)
	/// Proof: `X3WalletPallet::RecoveryAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3WalletPallet::RecoveryRequests` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_recovery() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `450`
		//  Estimated: `3915`
		// Minimum execution time: 48_064_000 picoseconds.
		Weight::from_parts(52_101_000, 3915)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::RecoveryAccounts` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3WalletPallet::RecoveryRequests` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn finalize_recovery() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `482`
		//  Estimated: `3947`
		// Minimum execution time: 52_235_000 picoseconds.
		Weight::from_parts(53_638_000, 3947)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3WalletPallet::RecoveryAccounts` (r:1 w:0)
	/// Proof: `X3WalletPallet::RecoveryAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3WalletPallet::RecoveryRequests` (r:1 w:1)
	/// Proof: `X3WalletPallet::RecoveryRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_recovery() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `450`
		//  Estimated: `3915`
		// Minimum execution time: 45_685_000 picoseconds.
		Weight::from_parts(46_760_000, 3915)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::Minters` (r:1 w:0)
	/// Proof: `X3WalletPallet::Minters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3WalletPallet::TokenBalances` (r:1 w:1)
	/// Proof: `X3WalletPallet::TokenBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn mint_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `150`
		//  Estimated: `3615`
		// Minimum execution time: 39_750_000 picoseconds.
		Weight::from_parts(40_754_000, 3615)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::Minters` (r:0 w:1)
	/// Proof: `X3WalletPallet::Minters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_minter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 14_291_000 picoseconds.
		Weight::from_parts(16_086_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3WalletPallet::Minters` (r:0 w:1)
	/// Proof: `X3WalletPallet::Minters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_minter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 13_502_000 picoseconds.
		Weight::from_parts(14_309_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
