// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_reconciliation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_reconciliation
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-reconciliation/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_reconciliation`.
pub trait WeightInfo {
	fn submit_chain_supply_report() -> Weight;
	fn set_canonical_supply() -> Weight;
	fn run_reconciliation() -> Weight;
	fn lift_mint_halt() -> Weight;
	fn update_governance_power() -> Weight;
	fn aggregate_governance_power() -> Weight;
}

/// Weights for `pallet_x3_reconciliation` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3Reconciliation::ChainSupplyReports` (r:0 w:1)
	/// Proof: `X3Reconciliation::ChainSupplyReports` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn submit_chain_supply_report() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 26_834_000 picoseconds.
		Weight::from_parts(28_533_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Reconciliation::CanonicalSupply` (r:0 w:1)
	/// Proof: `X3Reconciliation::CanonicalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_canonical_supply() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 20_885_000 picoseconds.
		Weight::from_parts(21_965_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Reconciliation::CanonicalSupply` (r:1 w:0)
	/// Proof: `X3Reconciliation::CanonicalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::ChainSupplyReports` (r:2 w:0)
	/// Proof: `X3Reconciliation::ChainSupplyReports` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::LastReconciliation` (r:0 w:1)
	/// Proof: `X3Reconciliation::LastReconciliation` (`max_values`: Some(1), `max_size`: Some(42), added: 537, mode: `MaxEncodedLen`)
	fn run_reconciliation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `247`
		//  Estimated: `6028`
		// Minimum execution time: 52_398_000 picoseconds.
		Weight::from_parts(55_257_000, 6028)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Reconciliation::MintHaltSince` (r:1 w:1)
	/// Proof: `X3Reconciliation::MintHaltSince` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::LastReconciliation` (r:1 w:0)
	/// Proof: `X3Reconciliation::LastReconciliation` (`max_values`: Some(1), `max_size`: Some(42), added: 537, mode: `MaxEncodedLen`)
	fn lift_mint_halt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `170`
		//  Estimated: `1527`
		// Minimum execution time: 34_033_000 picoseconds.
		Weight::from_parts(35_656_000, 1527)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Reconciliation::GovernancePowerByChain` (r:2 w:1)
	/// Proof: `X3Reconciliation::GovernancePowerByChain` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::TotalGovernancePower` (r:0 w:1)
	/// Proof: `X3Reconciliation::TotalGovernancePower` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn update_governance_power() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `146`
		//  Estimated: `6012`
		// Minimum execution time: 67_728_000 picoseconds.
		Weight::from_parts(75_095_000, 6012)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Reconciliation::GovernancePowerByChain` (r:3 w:0)
	/// Proof: `X3Reconciliation::GovernancePowerByChain` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::TotalGovernancePower` (r:0 w:1)
	/// Proof: `X3Reconciliation::TotalGovernancePower` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::LastPowerReconciliation` (r:0 w:1)
	/// Proof: `X3Reconciliation::LastPowerReconciliation` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn aggregate_governance_power() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `8523`
		// Minimum execution time: 55_349_000 picoseconds.
		Weight::from_parts(57_870_000, 8523)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3Reconciliation::ChainSupplyReports` (r:0 w:1)
	/// Proof: `X3Reconciliation::ChainSupplyReports` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn submit_chain_supply_report() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 26_834_000 picoseconds.
		Weight::from_parts(28_533_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Reconciliation::CanonicalSupply` (r:0 w:1)
	/// Proof: `X3Reconciliation::CanonicalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_canonical_supply() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 20_885_000 picoseconds.
		Weight::from_parts(21_965_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Reconciliation::CanonicalSupply` (r:1 w:0)
	/// Proof: `X3Reconciliation::CanonicalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::ChainSupplyReports` (r:2 w:0)
	/// Proof: `X3Reconciliation::ChainSupplyReports` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::LastReconciliation` (r:0 w:1)
	/// Proof: `X3Reconciliation::LastReconciliation` (`max_values`: Some(1), `max_size`: Some(42), added: 537, mode: `MaxEncodedLen`)
	fn run_reconciliation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `247`
		//  Estimated: `6028`
		// Minimum execution time: 52_398_000 picoseconds.
		Weight::from_parts(55_257_000, 6028)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Reconciliation::MintHaltSince` (r:1 w:1)
	/// Proof: `X3Reconciliation::MintHaltSince` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::LastReconciliation` (r:1 w:0)
	/// Proof: `X3Reconciliation::LastReconciliation` (`max_values`: Some(1), `max_size`: Some(42), added: 537, mode: `MaxEncodedLen`)
	fn lift_mint_halt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `170`
		//  Estimated: `1527`
		// Minimum execution time: 34_033_000 picoseconds.
		Weight::from_parts(35_656_000, 1527)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Reconciliation::GovernancePowerByChain` (r:2 w:1)
	/// Proof: `X3Reconciliation::GovernancePowerByChain` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::TotalGovernancePower` (r:0 w:1)
	/// Proof: `X3Reconciliation::TotalGovernancePower` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn update_governance_power() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `146`
		//  Estimated: `6012`
		// Minimum execution time: 67_728_000 picoseconds.
		Weight::from_parts(75_095_000, 6012)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Reconciliation::GovernancePowerByChain` (r:3 w:0)
	/// Proof: `X3Reconciliation::GovernancePowerByChain` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::TotalGovernancePower` (r:0 w:1)
	/// Proof: `X3Reconciliation::TotalGovernancePower` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reconciliation::LastPowerReconciliation` (r:0 w:1)
	/// Proof: `X3Reconciliation::LastPowerReconciliation` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn aggregate_governance_power() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `8523`
		// Minimum execution time: 55_349_000 picoseconds.
		Weight::from_parts(57_870_000, 8523)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
