// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_flashloan`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_flashloan
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-flashloan/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_flashloan`.
pub trait WeightInfo {
	fn add_liquidity() -> Weight;
	fn borrow() -> Weight;
	fn repay() -> Weight;
}

/// Weights for `pallet_x3_flashloan` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `X3FlashLoan::PoolBalance` (r:1 w:1)
	/// Proof: `X3FlashLoan::PoolBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn add_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44`
		//  Estimated: `3593`
		// Minimum execution time: 146_801_000 picoseconds.
		Weight::from_parts(147_936_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3FlashLoan::ActiveLoan` (r:1 w:1)
	/// Proof: `X3FlashLoan::ActiveLoan` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
	/// Storage: `X3FlashLoan::PoolBalance` (r:1 w:1)
	/// Proof: `X3FlashLoan::PoolBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn borrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `199`
		//  Estimated: `6196`
		// Minimum execution time: 157_135_000 picoseconds.
		Weight::from_parts(163_747_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `X3FlashLoan::ActiveLoan` (r:1 w:1)
	/// Proof: `X3FlashLoan::ActiveLoan` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `X3FlashLoan::PoolBalance` (r:1 w:1)
	/// Proof: `X3FlashLoan::PoolBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3FlashLoan::TotalFeesCollected` (r:1 w:1)
	/// Proof: `X3FlashLoan::TotalFeesCollected` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn repay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `375`
		//  Estimated: `6196`
		// Minimum execution time: 158_897_000 picoseconds.
		Weight::from_parts(166_452_000, 6196)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `X3FlashLoan::PoolBalance` (r:1 w:1)
	/// Proof: `X3FlashLoan::PoolBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn add_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44`
		//  Estimated: `3593`
		// Minimum execution time: 146_801_000 picoseconds.
		Weight::from_parts(147_936_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3FlashLoan::ActiveLoan` (r:1 w:1)
	/// Proof: `X3FlashLoan::ActiveLoan` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
	/// Storage: `X3FlashLoan::PoolBalance` (r:1 w:1)
	/// Proof: `X3FlashLoan::PoolBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn borrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `199`
		//  Estimated: `6196`
		// Minimum execution time: 157_135_000 picoseconds.
		Weight::from_parts(163_747_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `X3FlashLoan::ActiveLoan` (r:1 w:1)
	/// Proof: `X3FlashLoan::ActiveLoan` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `X3FlashLoan::PoolBalance` (r:1 w:1)
	/// Proof: `X3FlashLoan::PoolBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3FlashLoan::TotalFeesCollected` (r:1 w:1)
	/// Proof: `X3FlashLoan::TotalFeesCollected` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn repay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `375`
		//  Estimated: `6196`
		// Minimum execution time: 158_897_000 picoseconds.
		Weight::from_parts(166_452_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
}
