// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_dapp_hub`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_dapp_hub
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-dapp-hub/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_dapp_hub`.
pub trait WeightInfo {
	fn register_dapp() -> Weight;
	fn approve_dapp() -> Weight;
	fn reject_dapp() -> Weight;
	fn suspend_dapp() -> Weight;
	fn set_placement() -> Weight;
	fn record_revenue() -> Weight;
	fn set_revenue_policy() -> Weight;
	fn withdraw_earnings() -> Weight;
}

/// Weights for `pallet_x3_dapp_hub` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3DappHub::RevenuePolicies` (r:1 w:0)
	/// Proof: `X3DappHub::RevenuePolicies` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::TotalDApps` (r:1 w:1)
	/// Proof: `X3DappHub::TotalDApps` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::DeveloperDApps` (r:1 w:1)
	/// Proof: `X3DappHub::DeveloperDApps` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::NextDAppId` (r:1 w:1)
	/// Proof: `X3DappHub::NextDAppId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::DApps` (r:0 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn register_dapp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `3674`
		// Minimum execution time: 59_387_000 picoseconds.
		Weight::from_parts(60_112_000, 3674)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `X3DappHub::DApps` (r:1 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn approve_dapp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3575`
		// Minimum execution time: 38_963_000 picoseconds.
		Weight::from_parts(39_942_000, 3575)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3DappHub::DApps` (r:1 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn reject_dapp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3575`
		// Minimum execution time: 39_336_000 picoseconds.
		Weight::from_parts(39_807_000, 3575)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3DappHub::DApps` (r:1 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn suspend_dapp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3575`
		// Minimum execution time: 39_041_000 picoseconds.
		Weight::from_parts(42_241_000, 3575)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3DappHub::DApps` (r:1 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn set_placement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3575`
		// Minimum execution time: 39_127_000 picoseconds.
		Weight::from_parts(40_589_000, 3575)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3DappHub::DApps` (r:1 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::RevenuePolicies` (r:1 w:0)
	/// Proof: `X3DappHub::RevenuePolicies` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::DeveloperEarnings` (r:1 w:1)
	/// Proof: `X3DappHub::DeveloperEarnings` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn record_revenue() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `338`
		//  Estimated: `3575`
		// Minimum execution time: 58_467_000 picoseconds.
		Weight::from_parts(63_052_000, 3575)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3DappHub::RevenuePolicies` (r:0 w:1)
	/// Proof: `X3DappHub::RevenuePolicies` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn set_revenue_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 26_978_000 picoseconds.
		Weight::from_parts(27_790_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3DappHub::DeveloperEarnings` (r:1 w:1)
	/// Proof: `X3DappHub::DeveloperEarnings` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn withdraw_earnings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `268`
		//  Estimated: `3529`
		// Minimum execution time: 38_381_000 picoseconds.
		Weight::from_parts(39_127_000, 3529)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3DappHub::RevenuePolicies` (r:1 w:0)
	/// Proof: `X3DappHub::RevenuePolicies` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::TotalDApps` (r:1 w:1)
	/// Proof: `X3DappHub::TotalDApps` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::DeveloperDApps` (r:1 w:1)
	/// Proof: `X3DappHub::DeveloperDApps` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::NextDAppId` (r:1 w:1)
	/// Proof: `X3DappHub::NextDAppId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::DApps` (r:0 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn register_dapp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `3674`
		// Minimum execution time: 59_387_000 picoseconds.
		Weight::from_parts(60_112_000, 3674)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `X3DappHub::DApps` (r:1 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn approve_dapp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3575`
		// Minimum execution time: 38_963_000 picoseconds.
		Weight::from_parts(39_942_000, 3575)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3DappHub::DApps` (r:1 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn reject_dapp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3575`
		// Minimum execution time: 39_336_000 picoseconds.
		Weight::from_parts(39_807_000, 3575)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3DappHub::DApps` (r:1 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn suspend_dapp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3575`
		// Minimum execution time: 39_041_000 picoseconds.
		Weight::from_parts(42_241_000, 3575)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3DappHub::DApps` (r:1 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn set_placement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3575`
		// Minimum execution time: 39_127_000 picoseconds.
		Weight::from_parts(40_589_000, 3575)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3DappHub::DApps` (r:1 w:1)
	/// Proof: `X3DappHub::DApps` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::RevenuePolicies` (r:1 w:0)
	/// Proof: `X3DappHub::RevenuePolicies` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `X3DappHub::DeveloperEarnings` (r:1 w:1)
	/// Proof: `X3DappHub::DeveloperEarnings` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn record_revenue() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `338`
		//  Estimated: `3575`
		// Minimum execution time: 58_467_000 picoseconds.
		Weight::from_parts(63_052_000, 3575)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3DappHub::RevenuePolicies` (r:0 w:1)
	/// Proof: `X3DappHub::RevenuePolicies` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn set_revenue_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 26_978_000 picoseconds.
		Weight::from_parts(27_790_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3DappHub::DeveloperEarnings` (r:1 w:1)
	/// Proof: `X3DappHub::DeveloperEarnings` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn withdraw_earnings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `268`
		//  Estimated: `3529`
		// Minimum execution time: 38_381_000 picoseconds.
		Weight::from_parts(39_127_000, 3529)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
