// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_partner`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_partner
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-partner/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_partner`.
pub trait WeightInfo {
	fn register_partner() -> Weight;
	fn add_approved_lane() -> Weight;
	fn remove_approved_lane() -> Weight;
	fn update_health_metrics() -> Weight;
	fn record_exposure() -> Weight;
	fn suspend_partner() -> Weight;
	fn reinstate_partner() -> Weight;
	fn terminate_partner() -> Weight;
}

/// Weights for `pallet_x3_partner` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn register_partner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `214`
		//  Estimated: `5652`
		// Minimum execution time: 35_900_000 picoseconds.
		Weight::from_parts(39_209_000, 5652)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Inventory::Lanes` (r:1 w:0)
	/// Proof: `X3Inventory::Lanes` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	/// Storage: `X3Partner::LanePartners` (r:1 w:1)
	/// Proof: `X3Partner::LanePartners` (`max_values`: None, `max_size`: Some(1073), added: 3548, mode: `MaxEncodedLen`)
	fn add_approved_lane() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `595`
		//  Estimated: `5652`
		// Minimum execution time: 56_855_000 picoseconds.
		Weight::from_parts(59_101_000, 5652)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	/// Storage: `X3Partner::LanePartners` (r:1 w:1)
	/// Proof: `X3Partner::LanePartners` (`max_values`: None, `max_size`: Some(1073), added: 3548, mode: `MaxEncodedLen`)
	fn remove_approved_lane() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `518`
		//  Estimated: `5652`
		// Minimum execution time: 49_427_000 picoseconds.
		Weight::from_parts(54_543_000, 5652)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn update_health_metrics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5652`
		// Minimum execution time: 37_837_000 picoseconds.
		Weight::from_parts(38_958_000, 5652)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn record_exposure() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5652`
		// Minimum execution time: 37_576_000 picoseconds.
		Weight::from_parts(38_993_000, 5652)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn suspend_partner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5652`
		// Minimum execution time: 37_665_000 picoseconds.
		Weight::from_parts(40_520_000, 5652)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn reinstate_partner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5652`
		// Minimum execution time: 37_638_000 picoseconds.
		Weight::from_parts(38_655_000, 5652)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn terminate_partner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5652`
		// Minimum execution time: 37_384_000 picoseconds.
		Weight::from_parts(38_402_000, 5652)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn register_partner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `214`
		//  Estimated: `5652`
		// Minimum execution time: 35_900_000 picoseconds.
		Weight::from_parts(39_209_000, 5652)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Inventory::Lanes` (r:1 w:0)
	/// Proof: `X3Inventory::Lanes` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	/// Storage: `X3Partner::LanePartners` (r:1 w:1)
	/// Proof: `X3Partner::LanePartners` (`max_values`: None, `max_size`: Some(1073), added: 3548, mode: `MaxEncodedLen`)
	fn add_approved_lane() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `595`
		//  Estimated: `5652`
		// Minimum execution time: 56_855_000 picoseconds.
		Weight::from_parts(59_101_000, 5652)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	/// Storage: `X3Partner::LanePartners` (r:1 w:1)
	/// Proof: `X3Partner::LanePartners` (`max_values`: None, `max_size`: Some(1073), added: 3548, mode: `MaxEncodedLen`)
	fn remove_approved_lane() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `518`
		//  Estimated: `5652`
		// Minimum execution time: 49_427_000 picoseconds.
		Weight::from_parts(54_543_000, 5652)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn update_health_metrics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5652`
		// Minimum execution time: 37_837_000 picoseconds.
		Weight::from_parts(38_958_000, 5652)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn record_exposure() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5652`
		// Minimum execution time: 37_576_000 picoseconds.
		Weight::from_parts(38_993_000, 5652)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn suspend_partner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5652`
		// Minimum execution time: 37_665_000 picoseconds.
		Weight::from_parts(40_520_000, 5652)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn reinstate_partner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5652`
		// Minimum execution time: 37_638_000 picoseconds.
		Weight::from_parts(38_655_000, 5652)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Partner::Partners` (r:1 w:1)
	/// Proof: `X3Partner::Partners` (`max_values`: None, `max_size`: Some(2187), added: 4662, mode: `MaxEncodedLen`)
	fn terminate_partner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5652`
		// Minimum execution time: 37_384_000 picoseconds.
		Weight::from_parts(38_402_000, 5652)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
