// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_cross_vm_router`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_cross_vm_router
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-cross-vm-router/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_cross_vm_router`.
pub trait WeightInfo {
	fn set_external_bridge_audit_gate() -> Weight;
	fn set_external_bridges_enabled() -> Weight;
	fn emergency_pause_bridge() -> Weight;
}

/// Weights for `pallet_x3_cross_vm_router` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3CrossVmRouter::ExternalBridgeAuditGate` (r:0 w:1)
	/// Proof: `X3CrossVmRouter::ExternalBridgeAuditGate` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_external_bridge_audit_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 19_002_000 picoseconds.
		Weight::from_parts(19_424_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrossVmRouter::ExternalBridgeAuditGate` (r:1 w:0)
	/// Proof: `X3CrossVmRouter::ExternalBridgeAuditGate` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `X3CrossVmRouter::ExternalBridgesEnabled` (r:0 w:1)
	/// Proof: `X3CrossVmRouter::ExternalBridgesEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_external_bridges_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `166`
		//  Estimated: `1486`
		// Minimum execution time: 26_881_000 picoseconds.
		Weight::from_parts(27_634_000, 1486)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrossVmRouter::ExternalBridgesEnabled` (r:1 w:0)
	/// Proof: `X3CrossVmRouter::ExternalBridgesEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `X3CrossVmRouter::BridgePaused` (r:0 w:1)
	/// Proof: `X3CrossVmRouter::BridgePaused` (`max_values`: None, `max_size`: Some(278), added: 2753, mode: `MaxEncodedLen`)
	fn emergency_pause_bridge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `1486`
		// Minimum execution time: 33_573_000 picoseconds.
		Weight::from_parts(36_657_000, 1486)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3CrossVmRouter::ExternalBridgeAuditGate` (r:0 w:1)
	/// Proof: `X3CrossVmRouter::ExternalBridgeAuditGate` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_external_bridge_audit_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 19_002_000 picoseconds.
		Weight::from_parts(19_424_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrossVmRouter::ExternalBridgeAuditGate` (r:1 w:0)
	/// Proof: `X3CrossVmRouter::ExternalBridgeAuditGate` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `X3CrossVmRouter::ExternalBridgesEnabled` (r:0 w:1)
	/// Proof: `X3CrossVmRouter::ExternalBridgesEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_external_bridges_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `166`
		//  Estimated: `1486`
		// Minimum execution time: 26_881_000 picoseconds.
		Weight::from_parts(27_634_000, 1486)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrossVmRouter::ExternalBridgesEnabled` (r:1 w:0)
	/// Proof: `X3CrossVmRouter::ExternalBridgesEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `X3CrossVmRouter::BridgePaused` (r:0 w:1)
	/// Proof: `X3CrossVmRouter::BridgePaused` (`max_values`: None, `max_size`: Some(278), added: 2753, mode: `MaxEncodedLen`)
	fn emergency_pause_bridge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `1486`
		// Minimum execution time: 33_573_000 picoseconds.
		Weight::from_parts(36_657_000, 1486)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
