// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_custody`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_custody
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-custody/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_custody`.
pub trait WeightInfo {
	fn register_signer() -> Weight;
	fn deactivate_signer() -> Weight;
	fn register_validator_key() -> Weight;
	fn rotate_validator_key() -> Weight;
	fn set_tier_threshold() -> Weight;
	fn set_signer_limit() -> Weight;
	fn set_key_rotation_schedule() -> Weight;
	fn check_signer_authorized() -> Weight;
	fn authorize_gateway() -> Weight;
	fn revoke_gateway() -> Weight;
}

/// Weights for `pallet_x3_custody` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3Custody::CustodyMap` (r:1 w:1)
	/// Proof: `X3Custody::CustodyMap` (`max_values`: None, `max_size`: Some(601), added: 3076, mode: `MaxEncodedLen`)
	fn register_signer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `252`
		//  Estimated: `4066`
		// Minimum execution time: 40_417_000 picoseconds.
		Weight::from_parts(45_117_000, 4066)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::CustodyMap` (r:1 w:1)
	/// Proof: `X3Custody::CustodyMap` (`max_values`: None, `max_size`: Some(601), added: 3076, mode: `MaxEncodedLen`)
	fn deactivate_signer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `351`
		//  Estimated: `4066`
		// Minimum execution time: 43_380_000 picoseconds.
		Weight::from_parts(46_840_000, 4066)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::ValidatorKeyRegistry` (r:1 w:1)
	/// Proof: `X3Custody::ValidatorKeyRegistry` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `X3Custody::KeyRotationSchedule` (r:0 w:1)
	/// Proof: `X3Custody::KeyRotationSchedule` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn register_validator_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `252`
		//  Estimated: `3523`
		// Minimum execution time: 46_356_000 picoseconds.
		Weight::from_parts(49_681_000, 3523)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Custody::ValidatorKeyRegistry` (r:2 w:2)
	/// Proof: `X3Custody::ValidatorKeyRegistry` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `X3Custody::KeyRotationSchedule` (r:0 w:2)
	/// Proof: `X3Custody::KeyRotationSchedule` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn rotate_validator_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `365`
		//  Estimated: `6056`
		// Minimum execution time: 63_303_000 picoseconds.
		Weight::from_parts(71_365_000, 6056)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `X3Custody::TierThresholds` (r:0 w:1)
	/// Proof: `X3Custody::TierThresholds` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
	fn set_tier_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 27_374_000 picoseconds.
		Weight::from_parts(29_253_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::SignerLimits` (r:0 w:1)
	/// Proof: `X3Custody::SignerLimits` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	fn set_signer_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 27_882_000 picoseconds.
		Weight::from_parts(30_138_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::KeyRotationSchedule` (r:0 w:1)
	/// Proof: `X3Custody::KeyRotationSchedule` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn set_key_rotation_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 27_062_000 picoseconds.
		Weight::from_parts(29_767_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::CustodyMap` (r:1 w:0)
	/// Proof: `X3Custody::CustodyMap` (`max_values`: None, `max_size`: Some(601), added: 3076, mode: `MaxEncodedLen`)
	fn check_signer_authorized() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `351`
		//  Estimated: `4066`
		// Minimum execution time: 31_326_000 picoseconds.
		Weight::from_parts(34_003_000, 4066)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `X3Custody::AuthorizedGateways` (r:1 w:1)
	/// Proof: `X3Custody::AuthorizedGateways` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn authorize_gateway() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `3530`
		// Minimum execution time: 48_079_000 picoseconds.
		Weight::from_parts(52_079_000, 3530)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::AuthorizedGateways` (r:1 w:1)
	/// Proof: `X3Custody::AuthorizedGateways` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn revoke_gateway() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `380`
		//  Estimated: `3530`
		// Minimum execution time: 48_634_000 picoseconds.
		Weight::from_parts(52_581_000, 3530)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3Custody::CustodyMap` (r:1 w:1)
	/// Proof: `X3Custody::CustodyMap` (`max_values`: None, `max_size`: Some(601), added: 3076, mode: `MaxEncodedLen`)
	fn register_signer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `252`
		//  Estimated: `4066`
		// Minimum execution time: 40_417_000 picoseconds.
		Weight::from_parts(45_117_000, 4066)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::CustodyMap` (r:1 w:1)
	/// Proof: `X3Custody::CustodyMap` (`max_values`: None, `max_size`: Some(601), added: 3076, mode: `MaxEncodedLen`)
	fn deactivate_signer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `351`
		//  Estimated: `4066`
		// Minimum execution time: 43_380_000 picoseconds.
		Weight::from_parts(46_840_000, 4066)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::ValidatorKeyRegistry` (r:1 w:1)
	/// Proof: `X3Custody::ValidatorKeyRegistry` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `X3Custody::KeyRotationSchedule` (r:0 w:1)
	/// Proof: `X3Custody::KeyRotationSchedule` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn register_validator_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `252`
		//  Estimated: `3523`
		// Minimum execution time: 46_356_000 picoseconds.
		Weight::from_parts(49_681_000, 3523)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Custody::ValidatorKeyRegistry` (r:2 w:2)
	/// Proof: `X3Custody::ValidatorKeyRegistry` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `X3Custody::KeyRotationSchedule` (r:0 w:2)
	/// Proof: `X3Custody::KeyRotationSchedule` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn rotate_validator_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `365`
		//  Estimated: `6056`
		// Minimum execution time: 63_303_000 picoseconds.
		Weight::from_parts(71_365_000, 6056)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `X3Custody::TierThresholds` (r:0 w:1)
	/// Proof: `X3Custody::TierThresholds` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
	fn set_tier_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 27_374_000 picoseconds.
		Weight::from_parts(29_253_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::SignerLimits` (r:0 w:1)
	/// Proof: `X3Custody::SignerLimits` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	fn set_signer_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 27_882_000 picoseconds.
		Weight::from_parts(30_138_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::KeyRotationSchedule` (r:0 w:1)
	/// Proof: `X3Custody::KeyRotationSchedule` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn set_key_rotation_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 27_062_000 picoseconds.
		Weight::from_parts(29_767_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::CustodyMap` (r:1 w:0)
	/// Proof: `X3Custody::CustodyMap` (`max_values`: None, `max_size`: Some(601), added: 3076, mode: `MaxEncodedLen`)
	fn check_signer_authorized() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `351`
		//  Estimated: `4066`
		// Minimum execution time: 31_326_000 picoseconds.
		Weight::from_parts(34_003_000, 4066)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `X3Custody::AuthorizedGateways` (r:1 w:1)
	/// Proof: `X3Custody::AuthorizedGateways` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn authorize_gateway() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `3530`
		// Minimum execution time: 48_079_000 picoseconds.
		Weight::from_parts(52_079_000, 3530)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Custody::AuthorizedGateways` (r:1 w:1)
	/// Proof: `X3Custody::AuthorizedGateways` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn revoke_gateway() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `380`
		//  Estimated: `3530`
		// Minimum execution time: 48_634_000 picoseconds.
		Weight::from_parts(52_581_000, 3530)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
