// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_atomic_trade_engine`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_atomic_trade_engine
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/atomic-trade-engine/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_atomic_trade_engine`.
pub trait WeightInfo {
	fn create_trade_batch(l: u32, ) -> Weight;
	fn execute_trade_batch() -> Weight;
	fn cancel_trade_batch() -> Weight;
	fn register_amm_adapter() -> Weight;
	fn remove_amm_adapter() -> Weight;
	fn create_manual_checkpoint() -> Weight;
	fn register_liquidity_pool() -> Weight;
	fn update_liquidity_pool() -> Weight;
	fn sync_pool_price() -> Weight;
	fn submit_price_observation() -> Weight;
}

/// Weights for `pallet_atomic_trade_engine` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AtomicTradeEngine::TradeNonces` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::TradeNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::PendingBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::PendingBatches` (`max_values`: None, `max_size`: Some(2098), added: 4573, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::TradeBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::TradeBatches` (`max_values`: None, `max_size`: Some(6262), added: 8737, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 16]`.
	fn create_trade_batch(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `9727`
		// Minimum execution time: 63_047_000 picoseconds.
		Weight::from_parts(60_611_957, 9727)
			// Standard Error: 53_836
			.saturating_add(Weight::from_parts(4_598_090, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AtomicTradeEngine::TradeBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::TradeBatches` (`max_values`: None, `max_size`: Some(6262), added: 8737, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::Checkpoints` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::Checkpoints` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::PendingBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::PendingBatches` (`max_values`: None, `max_size`: Some(2098), added: 4573, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::FailedBatchCount` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::FailedBatchCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn execute_trade_batch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `764`
		//  Estimated: `9727`
		// Minimum execution time: 196_491_000 picoseconds.
		Weight::from_parts(218_680_000, 9727)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `AtomicTradeEngine::TradeBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::TradeBatches` (`max_values`: None, `max_size`: Some(6262), added: 8737, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::PendingBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::PendingBatches` (`max_values`: None, `max_size`: Some(2098), added: 4573, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::Checkpoints` (r:0 w:1)
	/// Proof: `AtomicTradeEngine::Checkpoints` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	fn cancel_trade_batch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `556`
		//  Estimated: `9727`
		// Minimum execution time: 47_433_000 picoseconds.
		Weight::from_parts(48_327_000, 9727)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AtomicTradeEngine::AmmAdapters` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::AmmAdapters` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	fn register_amm_adapter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3554`
		// Minimum execution time: 36_513_000 picoseconds.
		Weight::from_parts(38_630_000, 3554)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtomicTradeEngine::AmmAdapters` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::AmmAdapters` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	fn remove_amm_adapter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183`
		//  Estimated: `3554`
		// Minimum execution time: 35_250_000 picoseconds.
		Weight::from_parts(41_731_000, 3554)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtomicTradeEngine::TradeBatches` (r:1 w:0)
	/// Proof: `AtomicTradeEngine::TradeBatches` (`max_values`: None, `max_size`: Some(6262), added: 8737, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::Checkpoints` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::Checkpoints` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn create_manual_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `692`
		//  Estimated: `9727`
		// Minimum execution time: 78_106_000 picoseconds.
		Weight::from_parts(97_237_000, 9727)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtomicTradeEngine::LiquidityPools` (r:0 w:1)
	/// Proof: `AtomicTradeEngine::LiquidityPools` (`max_values`: None, `max_size`: Some(248), added: 2723, mode: `MaxEncodedLen`)
	fn register_liquidity_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 31_723_000 picoseconds.
		Weight::from_parts(34_722_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtomicTradeEngine::LiquidityPools` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::LiquidityPools` (`max_values`: None, `max_size`: Some(248), added: 2723, mode: `MaxEncodedLen`)
	fn update_liquidity_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `341`
		//  Estimated: `3713`
		// Minimum execution time: 40_129_000 picoseconds.
		Weight::from_parts(43_190_000, 3713)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::LiquidityPools` (r:1 w:0)
	/// Proof: `AtomicTradeEngine::LiquidityPools` (`max_values`: None, `max_size`: Some(248), added: 2723, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::PriceObservations` (r:2 w:2)
	/// Proof: `AtomicTradeEngine::PriceObservations` (`max_values`: None, `max_size`: Some(24914), added: 27389, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::TwapData` (r:2 w:2)
	/// Proof: `AtomicTradeEngine::TwapData` (`max_values`: None, `max_size`: Some(180), added: 2655, mode: `MaxEncodedLen`)
	fn sync_pool_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `549`
		//  Estimated: `55768`
		// Minimum execution time: 127_845_000 picoseconds.
		Weight::from_parts(142_132_000, 55768)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::PriceObservations` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::PriceObservations` (`max_values`: None, `max_size`: Some(24914), added: 27389, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::TwapData` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::TwapData` (`max_values`: None, `max_size`: Some(180), added: 2655, mode: `MaxEncodedLen`)
	fn submit_price_observation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `28379`
		// Minimum execution time: 83_660_000 picoseconds.
		Weight::from_parts(98_085_000, 28379)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `AtomicTradeEngine::TradeNonces` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::TradeNonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::PendingBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::PendingBatches` (`max_values`: None, `max_size`: Some(2098), added: 4573, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::TradeBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::TradeBatches` (`max_values`: None, `max_size`: Some(6262), added: 8737, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 16]`.
	fn create_trade_batch(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `9727`
		// Minimum execution time: 63_047_000 picoseconds.
		Weight::from_parts(60_611_957, 9727)
			// Standard Error: 53_836
			.saturating_add(Weight::from_parts(4_598_090, 0).saturating_mul(l.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AtomicTradeEngine::TradeBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::TradeBatches` (`max_values`: None, `max_size`: Some(6262), added: 8737, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::Checkpoints` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::Checkpoints` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::PendingBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::PendingBatches` (`max_values`: None, `max_size`: Some(2098), added: 4573, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::FailedBatchCount` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::FailedBatchCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn execute_trade_batch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `764`
		//  Estimated: `9727`
		// Minimum execution time: 196_491_000 picoseconds.
		Weight::from_parts(218_680_000, 9727)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `AtomicTradeEngine::TradeBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::TradeBatches` (`max_values`: None, `max_size`: Some(6262), added: 8737, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::PendingBatches` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::PendingBatches` (`max_values`: None, `max_size`: Some(2098), added: 4573, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::Checkpoints` (r:0 w:1)
	/// Proof: `AtomicTradeEngine::Checkpoints` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	fn cancel_trade_batch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `556`
		//  Estimated: `9727`
		// Minimum execution time: 47_433_000 picoseconds.
		Weight::from_parts(48_327_000, 9727)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AtomicTradeEngine::AmmAdapters` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::AmmAdapters` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	fn register_amm_adapter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3554`
		// Minimum execution time: 36_513_000 picoseconds.
		Weight::from_parts(38_630_000, 3554)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtomicTradeEngine::AmmAdapters` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::AmmAdapters` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	fn remove_amm_adapter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183`
		//  Estimated: `3554`
		// Minimum execution time: 35_250_000 picoseconds.
		Weight::from_parts(41_731_000, 3554)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtomicTradeEngine::TradeBatches` (r:1 w:0)
	/// Proof: `AtomicTradeEngine::TradeBatches` (`max_values`: None, `max_size`: Some(6262), added: 8737, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::Checkpoints` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::Checkpoints` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn create_manual_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `692`
		//  Estimated: `9727`
		// Minimum execution time: 78_106_000 picoseconds.
		Weight::from_parts(97_237_000, 9727)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtomicTradeEngine::LiquidityPools` (r:0 w:1)
	/// Proof: `AtomicTradeEngine::LiquidityPools` (`max_values`: None, `max_size`: Some(248), added: 2723, mode: `MaxEncodedLen`)
	fn register_liquidity_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 31_723_000 picoseconds.
		Weight::from_parts(34_722_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtomicTradeEngine::LiquidityPools` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::LiquidityPools` (`max_values`: None, `max_size`: Some(248), added: 2723, mode: `MaxEncodedLen`)
	fn update_liquidity_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `341`
		//  Estimated: `3713`
		// Minimum execution time: 40_129_000 picoseconds.
		Weight::from_parts(43_190_000, 3713)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::LiquidityPools` (r:1 w:0)
	/// Proof: `AtomicTradeEngine::LiquidityPools` (`max_values`: None, `max_size`: Some(248), added: 2723, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::PriceObservations` (r:2 w:2)
	/// Proof: `AtomicTradeEngine::PriceObservations` (`max_values`: None, `max_size`: Some(24914), added: 27389, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::TwapData` (r:2 w:2)
	/// Proof: `AtomicTradeEngine::TwapData` (`max_values`: None, `max_size`: Some(180), added: 2655, mode: `MaxEncodedLen`)
	fn sync_pool_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `549`
		//  Estimated: `55768`
		// Minimum execution time: 127_845_000 picoseconds.
		Weight::from_parts(142_132_000, 55768)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::PriceObservations` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::PriceObservations` (`max_values`: None, `max_size`: Some(24914), added: 27389, mode: `MaxEncodedLen`)
	/// Storage: `AtomicTradeEngine::TwapData` (r:1 w:1)
	/// Proof: `AtomicTradeEngine::TwapData` (`max_values`: None, `max_size`: Some(180), added: 2655, mode: `MaxEncodedLen`)
	fn submit_price_observation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `28379`
		// Minimum execution time: 83_660_000 picoseconds.
		Weight::from_parts(98_085_000, 28379)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
