// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_asset_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_asset_registry
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-asset-registry/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_asset_registry`.
pub trait WeightInfo {
	fn register_asset() -> Weight;
	fn activate_asset() -> Weight;
	fn pause_asset() -> Weight;
	fn unpause_asset() -> Weight;
	fn retire_asset() -> Weight;
	fn configure_route() -> Weight;
	fn set_route_enabled() -> Weight;
}

/// Weights for `pallet_x3_asset_registry` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3AssetRegistry::TotalAssets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::TotalAssets` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn register_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3728`
		// Minimum execution time: 52_492_000 picoseconds.
		Weight::from_parts(54_211_000, 3728)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn activate_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `259`
		//  Estimated: `3728`
		// Minimum execution time: 39_870_000 picoseconds.
		Weight::from_parts(43_866_000, 3728)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn pause_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `259`
		//  Estimated: `3728`
		// Minimum execution time: 36_786_000 picoseconds.
		Weight::from_parts(42_815_000, 3728)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn unpause_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `259`
		//  Estimated: `3728`
		// Minimum execution time: 36_573_000 picoseconds.
		Weight::from_parts(39_262_000, 3728)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn retire_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `259`
		//  Estimated: `3728`
		// Minimum execution time: 36_805_000 picoseconds.
		Weight::from_parts(37_763_000, 3728)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:0)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::Routes` (r:0 w:1)
	/// Proof: `X3AssetRegistry::Routes` (`max_values`: None, `max_size`: Some(142), added: 2617, mode: `MaxEncodedLen`)
	fn configure_route() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `193`
		//  Estimated: `3728`
		// Minimum execution time: 38_147_000 picoseconds.
		Weight::from_parts(40_496_000, 3728)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3AssetRegistry::Routes` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Routes` (`max_values`: None, `max_size`: Some(142), added: 2617, mode: `MaxEncodedLen`)
	fn set_route_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `305`
		//  Estimated: `3607`
		// Minimum execution time: 39_868_000 picoseconds.
		Weight::from_parts(41_378_000, 3607)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3AssetRegistry::TotalAssets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::TotalAssets` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn register_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3728`
		// Minimum execution time: 52_492_000 picoseconds.
		Weight::from_parts(54_211_000, 3728)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn activate_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `259`
		//  Estimated: `3728`
		// Minimum execution time: 39_870_000 picoseconds.
		Weight::from_parts(43_866_000, 3728)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn pause_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `259`
		//  Estimated: `3728`
		// Minimum execution time: 36_786_000 picoseconds.
		Weight::from_parts(42_815_000, 3728)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn unpause_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `259`
		//  Estimated: `3728`
		// Minimum execution time: 36_573_000 picoseconds.
		Weight::from_parts(39_262_000, 3728)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn retire_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `259`
		//  Estimated: `3728`
		// Minimum execution time: 36_805_000 picoseconds.
		Weight::from_parts(37_763_000, 3728)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:0)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::Routes` (r:0 w:1)
	/// Proof: `X3AssetRegistry::Routes` (`max_values`: None, `max_size`: Some(142), added: 2617, mode: `MaxEncodedLen`)
	fn configure_route() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `193`
		//  Estimated: `3728`
		// Minimum execution time: 38_147_000 picoseconds.
		Weight::from_parts(40_496_000, 3728)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3AssetRegistry::Routes` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Routes` (`max_values`: None, `max_size`: Some(142), added: 2617, mode: `MaxEncodedLen`)
	fn set_route_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `305`
		//  Estimated: `3607`
		// Minimum execution time: 39_868_000 picoseconds.
		Weight::from_parts(41_378_000, 3607)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
