[profile.dev]
codegen-units = 256
incremental = true

[profile.release]
codegen-units = 1
incremental = false
lto = false

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
