// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_reservation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_reservation
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-reservation/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_reservation`.
pub trait WeightInfo {
	fn request_reservation() -> Weight;
	fn release_reservation() -> Weight;
	fn consume_reservation() -> Weight;
}

/// Weights for `pallet_x3_reservation` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3Reservation::ReservationsByRoute` (r:1 w:1)
	/// Proof: `X3Reservation::ReservationsByRoute` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::Reservations` (r:1 w:1)
	/// Proof: `X3Reservation::Reservations` (`max_values`: None, `max_size`: Some(197), added: 2672, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::Lanes` (r:1 w:0)
	/// Proof: `X3Inventory::Lanes` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::Vaults` (r:1 w:1)
	/// Proof: `X3Inventory::Vaults` (`max_values`: None, `max_size`: Some(219), added: 2694, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::LaneUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::LaneUnsettledNotional` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::GlobalUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::GlobalUnsettledNotional` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::ExpiryQueue` (r:0 w:1)
	/// Proof: `X3Reservation::ExpiryQueue` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn request_reservation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `689`
		//  Estimated: `3684`
		// Minimum execution time: 109_648_000 picoseconds.
		Weight::from_parts(119_237_000, 3684)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `X3Reservation::Reservations` (r:1 w:1)
	/// Proof: `X3Reservation::Reservations` (`max_values`: None, `max_size`: Some(197), added: 2672, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::Vaults` (r:1 w:1)
	/// Proof: `X3Inventory::Vaults` (`max_values`: None, `max_size`: Some(219), added: 2694, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::LaneUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::LaneUnsettledNotional` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::GlobalUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::GlobalUnsettledNotional` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::ExpiryQueue` (r:0 w:1)
	/// Proof: `X3Reservation::ExpiryQueue` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::ReservationsByRoute` (r:0 w:1)
	/// Proof: `X3Reservation::ReservationsByRoute` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn release_reservation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `981`
		//  Estimated: `3684`
		// Minimum execution time: 103_332_000 picoseconds.
		Weight::from_parts(114_655_000, 3684)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `X3Reservation::Reservations` (r:1 w:1)
	/// Proof: `X3Reservation::Reservations` (`max_values`: None, `max_size`: Some(197), added: 2672, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::Vaults` (r:1 w:1)
	/// Proof: `X3Inventory::Vaults` (`max_values`: None, `max_size`: Some(219), added: 2694, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::LaneUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::LaneUnsettledNotional` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::GlobalUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::GlobalUnsettledNotional` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::ExpiryQueue` (r:0 w:1)
	/// Proof: `X3Reservation::ExpiryQueue` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::ReservationsByRoute` (r:0 w:1)
	/// Proof: `X3Reservation::ReservationsByRoute` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn consume_reservation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `981`
		//  Estimated: `3684`
		// Minimum execution time: 116_657_000 picoseconds.
		Weight::from_parts(125_602_000, 3684)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3Reservation::ReservationsByRoute` (r:1 w:1)
	/// Proof: `X3Reservation::ReservationsByRoute` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::Reservations` (r:1 w:1)
	/// Proof: `X3Reservation::Reservations` (`max_values`: None, `max_size`: Some(197), added: 2672, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::Lanes` (r:1 w:0)
	/// Proof: `X3Inventory::Lanes` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::Vaults` (r:1 w:1)
	/// Proof: `X3Inventory::Vaults` (`max_values`: None, `max_size`: Some(219), added: 2694, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::LaneUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::LaneUnsettledNotional` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::GlobalUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::GlobalUnsettledNotional` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::ExpiryQueue` (r:0 w:1)
	/// Proof: `X3Reservation::ExpiryQueue` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn request_reservation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `689`
		//  Estimated: `3684`
		// Minimum execution time: 109_648_000 picoseconds.
		Weight::from_parts(119_237_000, 3684)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `X3Reservation::Reservations` (r:1 w:1)
	/// Proof: `X3Reservation::Reservations` (`max_values`: None, `max_size`: Some(197), added: 2672, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::Vaults` (r:1 w:1)
	/// Proof: `X3Inventory::Vaults` (`max_values`: None, `max_size`: Some(219), added: 2694, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::LaneUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::LaneUnsettledNotional` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::GlobalUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::GlobalUnsettledNotional` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::ExpiryQueue` (r:0 w:1)
	/// Proof: `X3Reservation::ExpiryQueue` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::ReservationsByRoute` (r:0 w:1)
	/// Proof: `X3Reservation::ReservationsByRoute` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn release_reservation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `981`
		//  Estimated: `3684`
		// Minimum execution time: 103_332_000 picoseconds.
		Weight::from_parts(114_655_000, 3684)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `X3Reservation::Reservations` (r:1 w:1)
	/// Proof: `X3Reservation::Reservations` (`max_values`: None, `max_size`: Some(197), added: 2672, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::Vaults` (r:1 w:1)
	/// Proof: `X3Inventory::Vaults` (`max_values`: None, `max_size`: Some(219), added: 2694, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::LaneUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::LaneUnsettledNotional` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `X3Inventory::GlobalUnsettledNotional` (r:1 w:1)
	/// Proof: `X3Inventory::GlobalUnsettledNotional` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::ExpiryQueue` (r:0 w:1)
	/// Proof: `X3Reservation::ExpiryQueue` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `X3Reservation::ReservationsByRoute` (r:0 w:1)
	/// Proof: `X3Reservation::ReservationsByRoute` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn consume_reservation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `981`
		//  Estimated: `3684`
		// Minimum execution time: 116_657_000 picoseconds.
		Weight::from_parts(125_602_000, 3684)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
}
