// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_crosschain_gateway`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_crosschain_gateway
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-crosschain-gateway/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_crosschain_gateway`.
pub trait WeightInfo {
	fn register_asset() -> Weight;
	fn enable_route() -> Weight;
	fn disable_route() -> Weight;
	fn submit_deposit_proof() -> Weight;
	fn credit_x3_representation() -> Weight;
	fn request_withdrawal() -> Weight;
	fn burn_x3_representation() -> Weight;
	fn finalize_external_release() -> Weight;
	fn submit_release_proof() -> Weight;
	fn set_svm_validators() -> Weight;
	fn clear_svm_validators() -> Weight;
}

/// Weights for `pallet_x3_crosschain_gateway` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3CrosschainGateway::Assets` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::Assets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 25_974_000 picoseconds.
		Weight::from_parts(26_556_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::Assets` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::Assets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::Routes` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::Routes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn enable_route() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `178`
		//  Estimated: `3643`
		// Minimum execution time: 41_244_000 picoseconds.
		Weight::from_parts(42_564_000, 3643)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::Routes` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Routes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn disable_route() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `3829`
		// Minimum execution time: 39_560_000 picoseconds.
		Weight::from_parts(40_599_000, 3829)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::Routes` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Routes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::Assets` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::Assets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::UsedProofs` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::UsedProofs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::UsedNonces` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::UsedNonces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::ExternalLocked` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::ExternalLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::PendingWithdrawals` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::PendingWithdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::Transfers` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::Transfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_deposit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `490`
		//  Estimated: `3955`
		// Minimum execution time: 95_185_000 picoseconds.
		Weight::from_parts(97_411_000, 3955)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `X3CrosschainGateway::Transfers` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Transfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::Routes` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::Routes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn credit_x3_representation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `710`
		//  Estimated: `4175`
		// Minimum execution time: 56_177_000 picoseconds.
		Weight::from_parts(57_109_000, 4175)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::Withdrawals` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_withdrawal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 27_029_000 picoseconds.
		Weight::from_parts(27_659_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::Withdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::PendingWithdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::PendingWithdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::ExternalLocked` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::ExternalLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn burn_x3_representation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `3880`
		// Minimum execution time: 56_038_000 picoseconds.
		Weight::from_parts(57_546_000, 3880)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3CrosschainGateway::Withdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::ExternalLocked` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::ExternalLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::PendingWithdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::PendingWithdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn finalize_external_release() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `501`
		//  Estimated: `3966`
		// Minimum execution time: 63_026_000 picoseconds.
		Weight::from_parts(63_820_000, 3966)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `X3CrosschainGateway::Withdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::Routes` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::Routes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::ExternalLocked` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::ExternalLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::PendingWithdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::PendingWithdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_release_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `813`
		//  Estimated: `4278`
		// Minimum execution time: 81_220_000 picoseconds.
		Weight::from_parts(82_282_000, 4278)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `X3CrosschainGateway::SvmValidatorSets` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::SvmValidatorSets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_svm_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 23_993_000 picoseconds.
		Weight::from_parts(24_742_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::SvmValidatorSets` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::SvmValidatorSets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn clear_svm_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 22_174_000 picoseconds.
		Weight::from_parts(23_718_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3CrosschainGateway::Assets` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::Assets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 25_974_000 picoseconds.
		Weight::from_parts(26_556_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::Assets` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::Assets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::Routes` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::Routes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn enable_route() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `178`
		//  Estimated: `3643`
		// Minimum execution time: 41_244_000 picoseconds.
		Weight::from_parts(42_564_000, 3643)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::Routes` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Routes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn disable_route() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `3829`
		// Minimum execution time: 39_560_000 picoseconds.
		Weight::from_parts(40_599_000, 3829)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::Routes` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Routes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::Assets` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::Assets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::UsedProofs` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::UsedProofs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::UsedNonces` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::UsedNonces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::ExternalLocked` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::ExternalLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::PendingWithdrawals` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::PendingWithdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::Transfers` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::Transfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_deposit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `490`
		//  Estimated: `3955`
		// Minimum execution time: 95_185_000 picoseconds.
		Weight::from_parts(97_411_000, 3955)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `X3CrosschainGateway::Transfers` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Transfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::Routes` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::Routes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn credit_x3_representation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `710`
		//  Estimated: `4175`
		// Minimum execution time: 56_177_000 picoseconds.
		Weight::from_parts(57_109_000, 4175)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::Withdrawals` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_withdrawal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 27_029_000 picoseconds.
		Weight::from_parts(27_659_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::Withdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::PendingWithdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::PendingWithdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::ExternalLocked` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::ExternalLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn burn_x3_representation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `3880`
		// Minimum execution time: 56_038_000 picoseconds.
		Weight::from_parts(57_546_000, 3880)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3CrosschainGateway::Withdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::ExternalLocked` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::ExternalLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::PendingWithdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::PendingWithdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn finalize_external_release() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `501`
		//  Estimated: `3966`
		// Minimum execution time: 63_026_000 picoseconds.
		Weight::from_parts(63_820_000, 3966)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `X3CrosschainGateway::Withdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::Routes` (r:1 w:0)
	/// Proof: `X3CrosschainGateway::Routes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::ExternalLocked` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::ExternalLocked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `X3CrosschainGateway::PendingWithdrawals` (r:1 w:1)
	/// Proof: `X3CrosschainGateway::PendingWithdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_release_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `813`
		//  Estimated: `4278`
		// Minimum execution time: 81_220_000 picoseconds.
		Weight::from_parts(82_282_000, 4278)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `X3CrosschainGateway::SvmValidatorSets` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::SvmValidatorSets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_svm_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 23_993_000 picoseconds.
		Weight::from_parts(24_742_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3CrosschainGateway::SvmValidatorSets` (r:0 w:1)
	/// Proof: `X3CrosschainGateway::SvmValidatorSets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn clear_svm_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 22_174_000 picoseconds.
		Weight::from_parts(23_718_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
