// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_token_factory`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_token_factory
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-token-factory/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_token_factory`.
pub trait WeightInfo {
	fn create_token() -> Weight;
	fn mint() -> Weight;
	fn burn() -> Weight;
	fn transfer_mint_authority() -> Weight;
}

/// Weights for `pallet_x3_token_factory` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3SupplyLedger::TransferHalted` (r:1 w:0)
	/// Proof: `X3SupplyLedger::TransferHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `X3TokenFactory::FactoryNonce` (r:1 w:1)
	/// Proof: `X3TokenFactory::FactoryNonce` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::TotalAssets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::TotalAssets` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	/// Storage: `X3SupplyLedger::Ledgers` (r:1 w:1)
	/// Proof: `X3SupplyLedger::Ledgers` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::Routes` (r:0 w:2)
	/// Proof: `X3AssetRegistry::Routes` (`max_values`: None, `max_size`: Some(142), added: 2617, mode: `MaxEncodedLen`)
	/// Storage: `X3TokenFactory::Tokens` (r:0 w:1)
	/// Proof: `X3TokenFactory::Tokens` (`max_values`: None, `max_size`: Some(143), added: 2618, mode: `MaxEncodedLen`)
	fn create_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `3728`
		// Minimum execution time: 153_158_000 picoseconds.
		Weight::from_parts(161_313_000, 3728)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `X3SupplyLedger::TransferHalted` (r:1 w:0)
	/// Proof: `X3SupplyLedger::TransferHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAssets` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAssets` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAccounts` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAccounts` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:0)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3TokenFactory::Tokens` (r:1 w:0)
	/// Proof: `X3TokenFactory::Tokens` (`max_values`: None, `max_size`: Some(143), added: 2618, mode: `MaxEncodedLen`)
	/// Storage: `X3SupplyLedger::Ledgers` (r:1 w:1)
	/// Proof: `X3SupplyLedger::Ledgers` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:0)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `754`
		//  Estimated: `3728`
		// Minimum execution time: 109_985_000 picoseconds.
		Weight::from_parts(115_239_000, 3728)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3TokenFactory::Tokens` (r:1 w:0)
	/// Proof: `X3TokenFactory::Tokens` (`max_values`: None, `max_size`: Some(143), added: 2618, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAssets` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAssets` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAccounts` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAccounts` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:0)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3SupplyLedger::Ledgers` (r:1 w:1)
	/// Proof: `X3SupplyLedger::Ledgers` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `561`
		//  Estimated: `3609`
		// Minimum execution time: 90_946_000 picoseconds.
		Weight::from_parts(92_056_000, 3609)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3TokenFactory::Tokens` (r:1 w:1)
	/// Proof: `X3TokenFactory::Tokens` (`max_values`: None, `max_size`: Some(143), added: 2618, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAssets` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAssets` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAccounts` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAccounts` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:0)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn transfer_mint_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `385`
		//  Estimated: `3608`
		// Minimum execution time: 68_889_000 picoseconds.
		Weight::from_parts(70_572_000, 3608)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3SupplyLedger::TransferHalted` (r:1 w:0)
	/// Proof: `X3SupplyLedger::TransferHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `X3TokenFactory::FactoryNonce` (r:1 w:1)
	/// Proof: `X3TokenFactory::FactoryNonce` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::TotalAssets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::TotalAssets` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:1)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	/// Storage: `X3SupplyLedger::Ledgers` (r:1 w:1)
	/// Proof: `X3SupplyLedger::Ledgers` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::Routes` (r:0 w:2)
	/// Proof: `X3AssetRegistry::Routes` (`max_values`: None, `max_size`: Some(142), added: 2617, mode: `MaxEncodedLen`)
	/// Storage: `X3TokenFactory::Tokens` (r:0 w:1)
	/// Proof: `X3TokenFactory::Tokens` (`max_values`: None, `max_size`: Some(143), added: 2618, mode: `MaxEncodedLen`)
	fn create_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `3728`
		// Minimum execution time: 153_158_000 picoseconds.
		Weight::from_parts(161_313_000, 3728)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `X3SupplyLedger::TransferHalted` (r:1 w:0)
	/// Proof: `X3SupplyLedger::TransferHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAssets` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAssets` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAccounts` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAccounts` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:0)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3TokenFactory::Tokens` (r:1 w:0)
	/// Proof: `X3TokenFactory::Tokens` (`max_values`: None, `max_size`: Some(143), added: 2618, mode: `MaxEncodedLen`)
	/// Storage: `X3SupplyLedger::Ledgers` (r:1 w:1)
	/// Proof: `X3SupplyLedger::Ledgers` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:0)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `754`
		//  Estimated: `3728`
		// Minimum execution time: 109_985_000 picoseconds.
		Weight::from_parts(115_239_000, 3728)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3TokenFactory::Tokens` (r:1 w:0)
	/// Proof: `X3TokenFactory::Tokens` (`max_values`: None, `max_size`: Some(143), added: 2618, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAssets` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAssets` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAccounts` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAccounts` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:0)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3SupplyLedger::Ledgers` (r:1 w:1)
	/// Proof: `X3SupplyLedger::Ledgers` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `561`
		//  Estimated: `3609`
		// Minimum execution time: 90_946_000 picoseconds.
		Weight::from_parts(92_056_000, 3609)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3TokenFactory::Tokens` (r:1 w:1)
	/// Proof: `X3TokenFactory::Tokens` (`max_values`: None, `max_size`: Some(143), added: 2618, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAssets` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAssets` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::FrozenAccounts` (r:1 w:0)
	/// Proof: `X3Sentinel::FrozenAccounts` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:0)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn transfer_mint_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `385`
		//  Estimated: `3608`
		// Minimum execution time: 68_889_000 picoseconds.
		Weight::from_parts(70_572_000, 3608)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
