// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_supply_ledger`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_supply_ledger
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-supply-ledger/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_supply_ledger`.
pub trait WeightInfo {
	fn mint_canonical() -> Weight;
	fn burn_canonical() -> Weight;
	fn set_invariant_violation_policy() -> Weight;
	fn halt_transfers() -> Weight;
	fn resume_transfers() -> Weight;
}

/// Weights for `pallet_x3_supply_ledger` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:0)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	/// Storage: `X3SupplyLedger::Ledgers` (r:1 w:1)
	/// Proof: `X3SupplyLedger::Ledgers` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn mint_canonical() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `269`
		//  Estimated: `3728`
		// Minimum execution time: 48_734_000 picoseconds.
		Weight::from_parts(52_491_000, 3728)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3SupplyLedger::Ledgers` (r:1 w:1)
	/// Proof: `X3SupplyLedger::Ledgers` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn burn_canonical() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `3609`
		// Minimum execution time: 41_880_000 picoseconds.
		Weight::from_parts(42_445_000, 3609)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3SupplyLedger::InvariantPolicy` (r:0 w:1)
	/// Proof: `X3SupplyLedger::InvariantPolicy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_invariant_violation_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 21_201_000 picoseconds.
		Weight::from_parts(22_008_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3SupplyLedger::TransferHalted` (r:0 w:1)
	/// Proof: `X3SupplyLedger::TransferHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn halt_transfers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 21_614_000 picoseconds.
		Weight::from_parts(22_427_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3SupplyLedger::TransferHalted` (r:0 w:1)
	/// Proof: `X3SupplyLedger::TransferHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn resume_transfers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 20_661_000 picoseconds.
		Weight::from_parts(23_046_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3AssetRegistry::Assets` (r:1 w:0)
	/// Proof: `X3AssetRegistry::Assets` (`max_values`: None, `max_size`: Some(263), added: 2738, mode: `MaxEncodedLen`)
	/// Storage: `X3SupplyLedger::Ledgers` (r:1 w:1)
	/// Proof: `X3SupplyLedger::Ledgers` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn mint_canonical() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `269`
		//  Estimated: `3728`
		// Minimum execution time: 48_734_000 picoseconds.
		Weight::from_parts(52_491_000, 3728)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3SupplyLedger::Ledgers` (r:1 w:1)
	/// Proof: `X3SupplyLedger::Ledgers` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn burn_canonical() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `3609`
		// Minimum execution time: 41_880_000 picoseconds.
		Weight::from_parts(42_445_000, 3609)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3SupplyLedger::InvariantPolicy` (r:0 w:1)
	/// Proof: `X3SupplyLedger::InvariantPolicy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_invariant_violation_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 21_201_000 picoseconds.
		Weight::from_parts(22_008_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3SupplyLedger::TransferHalted` (r:0 w:1)
	/// Proof: `X3SupplyLedger::TransferHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn halt_transfers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 21_614_000 picoseconds.
		Weight::from_parts(22_427_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3SupplyLedger::TransferHalted` (r:0 w:1)
	/// Proof: `X3SupplyLedger::TransferHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn resume_transfers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 20_661_000 picoseconds.
		Weight::from_parts(23_046_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
