// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_sentinel`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_sentinel
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-sentinel/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_sentinel`.
pub trait WeightInfo {
	fn freeze_authority() -> Weight;
	fn unfreeze_authority() -> Weight;
	fn freeze_asset() -> Weight;
	fn unfreeze_asset() -> Weight;
	fn enroll_for_review() -> Weight;
	fn unenroll_from_review() -> Weight;
	fn grant_guardian_approval() -> Weight;
}

/// Weights for `pallet_x3_sentinel` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3Sentinel::FrozenAccounts` (r:1 w:1)
	/// Proof: `X3Sentinel::FrozenAccounts` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn freeze_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3561`
		// Minimum execution time: 37_632_000 picoseconds.
		Weight::from_parts(39_407_000, 3561)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Sentinel::FrozenAccounts` (r:1 w:1)
	/// Proof: `X3Sentinel::FrozenAccounts` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn unfreeze_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3561`
		// Minimum execution time: 40_896_000 picoseconds.
		Weight::from_parts(43_013_000, 3561)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Sentinel::FrozenAssets` (r:1 w:1)
	/// Proof: `X3Sentinel::FrozenAssets` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn freeze_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3513`
		// Minimum execution time: 35_001_000 picoseconds.
		Weight::from_parts(37_327_000, 3513)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Sentinel::FrozenAssets` (r:1 w:1)
	/// Proof: `X3Sentinel::FrozenAssets` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn unfreeze_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183`
		//  Estimated: `3513`
		// Minimum execution time: 37_295_000 picoseconds.
		Weight::from_parts(39_236_000, 3513)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:1)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::GuardApprovals` (r:0 w:1)
	/// Proof: `X3Sentinel::GuardApprovals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn enroll_for_review() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3513`
		// Minimum execution time: 38_359_000 picoseconds.
		Weight::from_parts(39_993_000, 3513)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:1)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::GuardApprovals` (r:0 w:1)
	/// Proof: `X3Sentinel::GuardApprovals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn unenroll_from_review() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `3513`
		// Minimum execution time: 41_271_000 picoseconds.
		Weight::from_parts(42_738_000, 3513)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:0)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::GuardApprovals` (r:1 w:1)
	/// Proof: `X3Sentinel::GuardApprovals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn grant_guardian_approval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `3521`
		// Minimum execution time: 46_355_000 picoseconds.
		Weight::from_parts(50_278_000, 3521)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3Sentinel::FrozenAccounts` (r:1 w:1)
	/// Proof: `X3Sentinel::FrozenAccounts` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn freeze_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3561`
		// Minimum execution time: 37_632_000 picoseconds.
		Weight::from_parts(39_407_000, 3561)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Sentinel::FrozenAccounts` (r:1 w:1)
	/// Proof: `X3Sentinel::FrozenAccounts` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn unfreeze_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3561`
		// Minimum execution time: 40_896_000 picoseconds.
		Weight::from_parts(43_013_000, 3561)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Sentinel::FrozenAssets` (r:1 w:1)
	/// Proof: `X3Sentinel::FrozenAssets` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn freeze_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3513`
		// Minimum execution time: 35_001_000 picoseconds.
		Weight::from_parts(37_327_000, 3513)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Sentinel::FrozenAssets` (r:1 w:1)
	/// Proof: `X3Sentinel::FrozenAssets` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn unfreeze_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183`
		//  Estimated: `3513`
		// Minimum execution time: 37_295_000 picoseconds.
		Weight::from_parts(39_236_000, 3513)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:1)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::GuardApprovals` (r:0 w:1)
	/// Proof: `X3Sentinel::GuardApprovals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn enroll_for_review() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3513`
		// Minimum execution time: 38_359_000 picoseconds.
		Weight::from_parts(39_993_000, 3513)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:1)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::GuardApprovals` (r:0 w:1)
	/// Proof: `X3Sentinel::GuardApprovals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn unenroll_from_review() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `3513`
		// Minimum execution time: 41_271_000 picoseconds.
		Weight::from_parts(42_738_000, 3513)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3Sentinel::ReviewEnrolled` (r:1 w:0)
	/// Proof: `X3Sentinel::ReviewEnrolled` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `X3Sentinel::GuardApprovals` (r:1 w:1)
	/// Proof: `X3Sentinel::GuardApprovals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn grant_guardian_approval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `3521`
		// Minimum execution time: 46_355_000 picoseconds.
		Weight::from_parts(50_278_000, 3521)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
