// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_wrapped`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_wrapped
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-wrapped/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_wrapped`.
pub trait WeightInfo {
	fn register_wrapped_asset() -> Weight;
	fn mint_wrapped() -> Weight;
	fn burn_wrapped() -> Weight;
	fn update_governance_power() -> Weight;
	fn pause_wrapped_asset() -> Weight;
	fn resume_wrapped_asset() -> Weight;
	fn set_bridge_fee() -> Weight;
}

/// Weights for `pallet_x3_wrapped` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:1)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	fn register_wrapped_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3570`
		// Minimum execution time: 34_058_000 picoseconds.
		Weight::from_parts(36_670_000, 3570)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Wrapped::BridgeNonces` (r:1 w:1)
	/// Proof: `X3Wrapped::BridgeNonces` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:0)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::WrappedSupply` (r:2 w:1)
	/// Proof: `X3Wrapped::WrappedSupply` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::WrappedBalances` (r:1 w:1)
	/// Proof: `X3Wrapped::WrappedBalances` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::TotalWrappedSupply` (r:1 w:1)
	/// Proof: `X3Wrapped::TotalWrappedSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn mint_wrapped() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `6092`
		// Minimum execution time: 83_509_000 picoseconds.
		Weight::from_parts(96_307_000, 6092)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:0)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::WrappedBalances` (r:1 w:1)
	/// Proof: `X3Wrapped::WrappedBalances` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::WrappedSupply` (r:1 w:1)
	/// Proof: `X3Wrapped::WrappedSupply` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::TotalWrappedSupply` (r:1 w:1)
	/// Proof: `X3Wrapped::TotalWrappedSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn burn_wrapped() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `592`
		//  Estimated: `3589`
		// Minimum execution time: 74_555_000 picoseconds.
		Weight::from_parts(75_455_000, 3589)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `X3Wrapped::WrappedBalances` (r:2 w:0)
	/// Proof: `X3Wrapped::WrappedBalances` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:0)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::GovernancePowerMap` (r:0 w:1)
	/// Proof: `X3Wrapped::GovernancePowerMap` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn update_governance_power() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `488`
		//  Estimated: `6188`
		// Minimum execution time: 55_380_000 picoseconds.
		Weight::from_parts(60_199_000, 6188)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:1)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	fn pause_wrapped_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `3570`
		// Minimum execution time: 35_413_000 picoseconds.
		Weight::from_parts(35_931_000, 3570)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:1)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	fn resume_wrapped_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `3570`
		// Minimum execution time: 35_298_000 picoseconds.
		Weight::from_parts(35_938_000, 3570)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:1)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	fn set_bridge_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `3570`
		// Minimum execution time: 35_377_000 picoseconds.
		Weight::from_parts(37_926_000, 3570)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:1)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	fn register_wrapped_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3570`
		// Minimum execution time: 34_058_000 picoseconds.
		Weight::from_parts(36_670_000, 3570)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Wrapped::BridgeNonces` (r:1 w:1)
	/// Proof: `X3Wrapped::BridgeNonces` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:0)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::WrappedSupply` (r:2 w:1)
	/// Proof: `X3Wrapped::WrappedSupply` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::WrappedBalances` (r:1 w:1)
	/// Proof: `X3Wrapped::WrappedBalances` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::TotalWrappedSupply` (r:1 w:1)
	/// Proof: `X3Wrapped::TotalWrappedSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn mint_wrapped() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `6092`
		// Minimum execution time: 83_509_000 picoseconds.
		Weight::from_parts(96_307_000, 6092)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:0)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::WrappedBalances` (r:1 w:1)
	/// Proof: `X3Wrapped::WrappedBalances` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::WrappedSupply` (r:1 w:1)
	/// Proof: `X3Wrapped::WrappedSupply` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::TotalWrappedSupply` (r:1 w:1)
	/// Proof: `X3Wrapped::TotalWrappedSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn burn_wrapped() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `592`
		//  Estimated: `3589`
		// Minimum execution time: 74_555_000 picoseconds.
		Weight::from_parts(75_455_000, 3589)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `X3Wrapped::WrappedBalances` (r:2 w:0)
	/// Proof: `X3Wrapped::WrappedBalances` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:0)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `X3Wrapped::GovernancePowerMap` (r:0 w:1)
	/// Proof: `X3Wrapped::GovernancePowerMap` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn update_governance_power() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `488`
		//  Estimated: `6188`
		// Minimum execution time: 55_380_000 picoseconds.
		Weight::from_parts(60_199_000, 6188)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:1)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	fn pause_wrapped_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `3570`
		// Minimum execution time: 35_413_000 picoseconds.
		Weight::from_parts(35_931_000, 3570)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:1)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	fn resume_wrapped_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `3570`
		// Minimum execution time: 35_298_000 picoseconds.
		Weight::from_parts(35_938_000, 3570)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Wrapped::RegisteredWrappedAssets` (r:1 w:1)
	/// Proof: `X3Wrapped::RegisteredWrappedAssets` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	fn set_bridge_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `3570`
		// Minimum execution time: 35_377_000 picoseconds.
		Weight::from_parts(37_926_000, 3570)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
