// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_treasury_policy`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_treasury_policy
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-treasury-policy/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_treasury_policy`.
pub trait WeightInfo {
	fn set_allocation_cap() -> Weight;
	fn set_operator_funding_threshold() -> Weight;
	fn fund_settlement_vault() -> Weight;
	fn approve_governance_action() -> Weight;
	fn reject_governance_action() -> Weight;
	fn withdraw_from_vault() -> Weight;
	fn deposit_insurance_reserve() -> Weight;
	fn withdraw_insurance_reserve() -> Weight;
}

/// Weights for `pallet_x3_treasury_policy` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3TreasuryPolicy::AllocationCaps` (r:0 w:1)
	/// Proof: `X3TreasuryPolicy::AllocationCaps` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	fn set_allocation_cap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 22_181_000 picoseconds.
		Weight::from_parts(23_760_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3TreasuryPolicy::OperatorFundingThreshold` (r:0 w:1)
	/// Proof: `X3TreasuryPolicy::OperatorFundingThreshold` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_operator_funding_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 17_881_000 picoseconds.
		Weight::from_parts(18_524_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Inventory::Vaults` (r:1 w:0)
	/// Proof: `X3Inventory::Vaults` (`max_values`: None, `max_size`: Some(219), added: 2694, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::AllocationCaps` (r:1 w:0)
	/// Proof: `X3TreasuryPolicy::AllocationCaps` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::OperatorFundingThreshold` (r:1 w:0)
	/// Proof: `X3TreasuryPolicy::OperatorFundingThreshold` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn fund_settlement_vault() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `667`
		//  Estimated: `3684`
		// Minimum execution time: 61_193_000 picoseconds.
		Weight::from_parts(62_198_000, 3684)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3TreasuryPolicy::PendingGovernanceActions` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::PendingGovernanceActions` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn approve_governance_action() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `303`
		//  Estimated: `3534`
		// Minimum execution time: 41_312_000 picoseconds.
		Weight::from_parts(45_393_000, 3534)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `X3TreasuryPolicy::PendingGovernanceActions` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::PendingGovernanceActions` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn reject_governance_action() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `303`
		//  Estimated: `3534`
		// Minimum execution time: 33_049_000 picoseconds.
		Weight::from_parts(33_798_000, 3534)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn withdraw_from_vault() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266`
		//  Estimated: `3498`
		// Minimum execution time: 35_119_000 picoseconds.
		Weight::from_parts(35_830_000, 3498)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X3TreasuryPolicy::InsuranceReserveBalance` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::InsuranceReserveBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn deposit_insurance_reserve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `208`
		//  Estimated: `1501`
		// Minimum execution time: 24_563_000 picoseconds.
		Weight::from_parts(26_295_000, 1501)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3TreasuryPolicy::InsuranceReserveBalance` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::InsuranceReserveBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn withdraw_insurance_reserve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `1501`
		// Minimum execution time: 27_498_000 picoseconds.
		Weight::from_parts(28_442_000, 1501)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3TreasuryPolicy::AllocationCaps` (r:0 w:1)
	/// Proof: `X3TreasuryPolicy::AllocationCaps` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	fn set_allocation_cap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 22_181_000 picoseconds.
		Weight::from_parts(23_760_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3TreasuryPolicy::OperatorFundingThreshold` (r:0 w:1)
	/// Proof: `X3TreasuryPolicy::OperatorFundingThreshold` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_operator_funding_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 17_881_000 picoseconds.
		Weight::from_parts(18_524_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Inventory::Vaults` (r:1 w:0)
	/// Proof: `X3Inventory::Vaults` (`max_values`: None, `max_size`: Some(219), added: 2694, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::AllocationCaps` (r:1 w:0)
	/// Proof: `X3TreasuryPolicy::AllocationCaps` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::OperatorFundingThreshold` (r:1 w:0)
	/// Proof: `X3TreasuryPolicy::OperatorFundingThreshold` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn fund_settlement_vault() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `667`
		//  Estimated: `3684`
		// Minimum execution time: 61_193_000 picoseconds.
		Weight::from_parts(62_198_000, 3684)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3TreasuryPolicy::PendingGovernanceActions` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::PendingGovernanceActions` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn approve_governance_action() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `303`
		//  Estimated: `3534`
		// Minimum execution time: 41_312_000 picoseconds.
		Weight::from_parts(45_393_000, 3534)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `X3TreasuryPolicy::PendingGovernanceActions` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::PendingGovernanceActions` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn reject_governance_action() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `303`
		//  Estimated: `3534`
		// Minimum execution time: 33_049_000 picoseconds.
		Weight::from_parts(33_798_000, 3534)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TreasuryDeployedByLaneClass` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::TotalDeployedSettlementFloat` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn withdraw_from_vault() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266`
		//  Estimated: `3498`
		// Minimum execution time: 35_119_000 picoseconds.
		Weight::from_parts(35_830_000, 3498)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X3TreasuryPolicy::InsuranceReserveBalance` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::InsuranceReserveBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn deposit_insurance_reserve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `208`
		//  Estimated: `1501`
		// Minimum execution time: 24_563_000 picoseconds.
		Weight::from_parts(26_295_000, 1501)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3TreasuryPolicy::InsuranceReserveBalance` (r:1 w:1)
	/// Proof: `X3TreasuryPolicy::InsuranceReserveBalance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn withdraw_insurance_reserve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `1501`
		// Minimum execution time: 27_498_000 picoseconds.
		Weight::from_parts(28_442_000, 1501)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
