// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_kernel`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_kernel
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-kernel/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_kernel`.
pub trait WeightInfo {
	fn submit_comit() -> Weight;
	fn submit_comit_v2() -> Weight;
	fn register_asset() -> Weight;
	fn update_canonical_balance() -> Weight;
	fn authorize_account() -> Weight;
	fn deauthorize_account() -> Weight;
	fn add_authority() -> Weight;
	fn remove_authority() -> Weight;
	fn schedule_authority_change() -> Weight;
	fn enact_authority_change() -> Weight;
	fn emergency_pause() -> Weight;
	fn emergency_unpause() -> Weight;
	fn emergency_halt() -> Weight;
	fn x3_execute(g: u32, ) -> Weight;
}

/// Weights for `pallet_x3_kernel` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AtlasKernel::ProtocolPaused` (r:1 w:0)
	/// Proof: `AtlasKernel::ProtocolPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::SubmittedComits` (r:1 w:1)
	/// Proof: `AtlasKernel::SubmittedComits` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::SubmissionsPerBlock` (r:1 w:1)
	/// Proof: `AtlasKernel::SubmissionsPerBlock` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::Nonces` (r:1 w:1)
	/// Proof: `AtlasKernel::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::AccountRegistry` (r:1 w:1)
	/// Proof: `AtlasKernel::AccountRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn submit_comit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `456`
		//  Estimated: `3545`
		// Minimum execution time: 206_846_000 picoseconds.
		Weight::from_parts(265_078_000, 3545)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `AtlasKernel::ProtocolPaused` (r:1 w:0)
	/// Proof: `AtlasKernel::ProtocolPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::SubmittedComits` (r:1 w:1)
	/// Proof: `AtlasKernel::SubmittedComits` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::SubmissionsPerBlock` (r:1 w:1)
	/// Proof: `AtlasKernel::SubmissionsPerBlock` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::Nonces` (r:1 w:1)
	/// Proof: `AtlasKernel::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::X3ContractStorage` (r:1 w:0)
	/// Proof: `AtlasKernel::X3ContractStorage` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `PrivateExecution::Enabled` (r:1 w:0)
	/// Proof: `PrivateExecution::Enabled` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AtlasKernel::AccountRegistry` (r:1 w:1)
	/// Proof: `AtlasKernel::AccountRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::X3ExecutionReceipts` (r:0 w:1)
	/// Proof: `AtlasKernel::X3ExecutionReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_comit_v2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `484`
		//  Estimated: `3545`
		// Minimum execution time: 234_176_000 picoseconds.
		Weight::from_parts(286_923_000, 3545)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `AtlasKernel::AssetRegistry` (r:1 w:1)
	/// Proof: `AtlasKernel::AssetRegistry` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	fn register_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3503`
		// Minimum execution time: 36_341_000 picoseconds.
		Weight::from_parts(40_642_000, 3503)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::AssetRegistry` (r:1 w:0)
	/// Proof: `AtlasKernel::AssetRegistry` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::CanonicalLedger` (r:0 w:1)
	/// Proof: `AtlasKernel::CanonicalLedger` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn update_canonical_balance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `278`
		//  Estimated: `3503`
		// Minimum execution time: 39_425_000 picoseconds.
		Weight::from_parts(41_501_000, 3503)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::AuthorizedAccounts` (r:0 w:1)
	/// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn authorize_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 23_706_000 picoseconds.
		Weight::from_parts(25_868_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::AuthorizedAccounts` (r:0 w:1)
	/// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn deauthorize_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 23_634_000 picoseconds.
		Weight::from_parts(26_085_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::Authorities` (r:1 w:1)
	/// Proof: `AtlasKernel::Authorities` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	fn add_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1765`
		//  Estimated: `4687`
		// Minimum execution time: 35_901_000 picoseconds.
		Weight::from_parts(38_768_000, 4687)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::Authorities` (r:1 w:1)
	/// Proof: `AtlasKernel::Authorities` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	fn remove_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1765`
		//  Estimated: `4687`
		// Minimum execution time: 36_062_000 picoseconds.
		Weight::from_parts(40_517_000, 4687)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::PendingAuthorities` (r:0 w:1)
	/// Proof: `AtlasKernel::PendingAuthorities` (`max_values`: Some(1), `max_size`: Some(3203), added: 3698, mode: `MaxEncodedLen`)
	fn schedule_authority_change() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 26_630_000 picoseconds.
		Weight::from_parts(31_231_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::PendingAuthorities` (r:1 w:1)
	/// Proof: `AtlasKernel::PendingAuthorities` (`max_values`: Some(1), `max_size`: Some(3203), added: 3698, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::Authorities` (r:0 w:1)
	/// Proof: `AtlasKernel::Authorities` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	fn enact_authority_change() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1802`
		//  Estimated: `4688`
		// Minimum execution time: 42_668_000 picoseconds.
		Weight::from_parts(45_517_000, 4688)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AtlasKernel::ProtocolPaused` (r:1 w:1)
	/// Proof: `AtlasKernel::ProtocolPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn emergency_pause() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `174`
		//  Estimated: `1486`
		// Minimum execution time: 26_774_000 picoseconds.
		Weight::from_parts(28_980_000, 1486)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::ProtocolPaused` (r:1 w:1)
	/// Proof: `AtlasKernel::ProtocolPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn emergency_unpause() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `194`
		//  Estimated: `1486`
		// Minimum execution time: 26_760_000 picoseconds.
		Weight::from_parts(30_288_000, 1486)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Invariants::Halted` (r:0 w:1)
	/// Proof: `X3Invariants::Halted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `X3SupplyLedger::TransferHalted` (r:0 w:1)
	/// Proof: `X3SupplyLedger::TransferHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn emergency_halt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 20_335_000 picoseconds.
		Weight::from_parts(23_517_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Running an X3 program for `g` gas on the chain's engine. Measured 2026-09-26 with
	/// `x3-chain-node benchmark pallet --pallet pallet_x3_kernel --extrinsic x3_execute --steps 10
	/// --repeat 5` in the wasm executor: 573.7 µs + 22.95 ns per gas (6,000,000 gas: 137.4 ms).
	/// The range of `g` is `[1000, 6000000]`.
	fn x3_execute(g: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 33_780_000 picoseconds.
		Weight::from_parts(573_703_649, 0)
			// Standard Error: 108
			.saturating_add(Weight::from_parts(22_950, 0).saturating_mul(g.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `AtlasKernel::ProtocolPaused` (r:1 w:0)
	/// Proof: `AtlasKernel::ProtocolPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::SubmittedComits` (r:1 w:1)
	/// Proof: `AtlasKernel::SubmittedComits` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::SubmissionsPerBlock` (r:1 w:1)
	/// Proof: `AtlasKernel::SubmissionsPerBlock` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::Nonces` (r:1 w:1)
	/// Proof: `AtlasKernel::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::AccountRegistry` (r:1 w:1)
	/// Proof: `AtlasKernel::AccountRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn submit_comit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `456`
		//  Estimated: `3545`
		// Minimum execution time: 206_846_000 picoseconds.
		Weight::from_parts(265_078_000, 3545)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `AtlasKernel::ProtocolPaused` (r:1 w:0)
	/// Proof: `AtlasKernel::ProtocolPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::SubmittedComits` (r:1 w:1)
	/// Proof: `AtlasKernel::SubmittedComits` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::SubmissionsPerBlock` (r:1 w:1)
	/// Proof: `AtlasKernel::SubmissionsPerBlock` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::Nonces` (r:1 w:1)
	/// Proof: `AtlasKernel::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::X3ContractStorage` (r:1 w:0)
	/// Proof: `AtlasKernel::X3ContractStorage` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `PrivateExecution::Enabled` (r:1 w:0)
	/// Proof: `PrivateExecution::Enabled` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AtlasKernel::AccountRegistry` (r:1 w:1)
	/// Proof: `AtlasKernel::AccountRegistry` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::X3ExecutionReceipts` (r:0 w:1)
	/// Proof: `AtlasKernel::X3ExecutionReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_comit_v2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `484`
		//  Estimated: `3545`
		// Minimum execution time: 234_176_000 picoseconds.
		Weight::from_parts(286_923_000, 3545)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `AtlasKernel::AssetRegistry` (r:1 w:1)
	/// Proof: `AtlasKernel::AssetRegistry` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	fn register_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3503`
		// Minimum execution time: 36_341_000 picoseconds.
		Weight::from_parts(40_642_000, 3503)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::AssetRegistry` (r:1 w:0)
	/// Proof: `AtlasKernel::AssetRegistry` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::CanonicalLedger` (r:0 w:1)
	/// Proof: `AtlasKernel::CanonicalLedger` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn update_canonical_balance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `278`
		//  Estimated: `3503`
		// Minimum execution time: 39_425_000 picoseconds.
		Weight::from_parts(41_501_000, 3503)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::AuthorizedAccounts` (r:0 w:1)
	/// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn authorize_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 23_706_000 picoseconds.
		Weight::from_parts(25_868_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::AuthorizedAccounts` (r:0 w:1)
	/// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn deauthorize_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 23_634_000 picoseconds.
		Weight::from_parts(26_085_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::Authorities` (r:1 w:1)
	/// Proof: `AtlasKernel::Authorities` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	fn add_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1765`
		//  Estimated: `4687`
		// Minimum execution time: 35_901_000 picoseconds.
		Weight::from_parts(38_768_000, 4687)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::Authorities` (r:1 w:1)
	/// Proof: `AtlasKernel::Authorities` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	fn remove_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1765`
		//  Estimated: `4687`
		// Minimum execution time: 36_062_000 picoseconds.
		Weight::from_parts(40_517_000, 4687)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::PendingAuthorities` (r:0 w:1)
	/// Proof: `AtlasKernel::PendingAuthorities` (`max_values`: Some(1), `max_size`: Some(3203), added: 3698, mode: `MaxEncodedLen`)
	fn schedule_authority_change() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 26_630_000 picoseconds.
		Weight::from_parts(31_231_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::PendingAuthorities` (r:1 w:1)
	/// Proof: `AtlasKernel::PendingAuthorities` (`max_values`: Some(1), `max_size`: Some(3203), added: 3698, mode: `MaxEncodedLen`)
	/// Storage: `AtlasKernel::Authorities` (r:0 w:1)
	/// Proof: `AtlasKernel::Authorities` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	fn enact_authority_change() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1802`
		//  Estimated: `4688`
		// Minimum execution time: 42_668_000 picoseconds.
		Weight::from_parts(45_517_000, 4688)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AtlasKernel::ProtocolPaused` (r:1 w:1)
	/// Proof: `AtlasKernel::ProtocolPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn emergency_pause() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `174`
		//  Estimated: `1486`
		// Minimum execution time: 26_774_000 picoseconds.
		Weight::from_parts(28_980_000, 1486)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AtlasKernel::ProtocolPaused` (r:1 w:1)
	/// Proof: `AtlasKernel::ProtocolPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn emergency_unpause() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `194`
		//  Estimated: `1486`
		// Minimum execution time: 26_760_000 picoseconds.
		Weight::from_parts(30_288_000, 1486)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `X3Invariants::Halted` (r:0 w:1)
	/// Proof: `X3Invariants::Halted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `X3SupplyLedger::TransferHalted` (r:0 w:1)
	/// Proof: `X3SupplyLedger::TransferHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn emergency_halt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 20_335_000 picoseconds.
		Weight::from_parts(23_517_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Running an X3 program for `g` gas on the chain's engine. Measured 2026-09-26 with
	/// `x3-chain-node benchmark pallet --pallet pallet_x3_kernel --extrinsic x3_execute --steps 10
	/// --repeat 5` in the wasm executor: 573.7 µs + 22.95 ns per gas (6,000,000 gas: 137.4 ms).
	/// The range of `g` is `[1000, 6000000]`.
	fn x3_execute(g: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 33_780_000 picoseconds.
		Weight::from_parts(573_703_649, 0)
			// Standard Error: 108
			.saturating_add(Weight::from_parts(22_950, 0).saturating_mul(g.into()))
	}
}
