// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_x3_sequencer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/x3-chain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_x3_sequencer
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x3-sequencer/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_sequencer`.
pub trait WeightInfo {
	fn submit_transaction() -> Weight;
}

/// Weights for `pallet_x3_sequencer` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X3Sequencer::GlobalSequence` (r:1 w:1)
	/// Proof: `X3Sequencer::GlobalSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X3Sequencer::PendingTxs` (r:1 w:1)
	/// Proof: `X3Sequencer::PendingTxs` (`max_values`: Some(1), `max_size`: Some(106498), added: 106993, mode: `MaxEncodedLen`)
	fn submit_transaction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `107983`
		// Minimum execution time: 67_580_000 picoseconds.
		Weight::from_parts(68_990_000, 107983)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X3Sequencer::GlobalSequence` (r:1 w:1)
	/// Proof: `X3Sequencer::GlobalSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X3Sequencer::PendingTxs` (r:1 w:1)
	/// Proof: `X3Sequencer::PendingTxs` (`max_values`: Some(1), `max_size`: Some(106498), added: 106993, mode: `MaxEncodedLen`)
	fn submit_transaction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `107983`
		// Minimum execution time: 67_580_000 picoseconds.
		Weight::from_parts(68_990_000, 107983)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
