//! Autogenerated weights for `pallet_northern_swarm`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: ``, HIGH RANGE: ``
//! WORST CASE MAP SIZE: ``
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev")
//! DB CACHE: 1024

// Executed Command:
// /home/lojak/actions-runner/_work/xxxstar/xxxstar/target/release/x3-chain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet-northern-swarm
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/lojak/actions-runner/_work/xxxstar/xxxstar/.maintain/frame-weight-template.hbs
// --output
// /home/lojak/actions-runner/_work/xxxstar/xxxstar/pallets/northern-swarm/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions for `pallet_northern_swarm`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_northern_swarm::WeightInfo for WeightInfo<T> {
	/// Storage:  (r: w:)
	/// Proof:  ()
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn register_executor(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  ``
		//  Estimated: ``
		// Minimum execution time: 145626_000 picoseconds.
		Weight::from_parts(163908000, )
			.saturating_add(DbWeight::get().reads(1 as u64))
			.saturating_add(DbWeight::get().writes(1 as u64))
	}
	/// Storage:  (r: w:)
	/// Proof:  ()
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ClaimedTaskCount` (r:1 w:0)
	/// Proof: `NorthernSwarm::ClaimedTaskCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn deregister_executor(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  ``
		//  Estimated: ``
		// Minimum execution time: 88077_000 picoseconds.
		Weight::from_parts(95953000, )
			.saturating_add(DbWeight::get().reads(2 as u64))
			.saturating_add(DbWeight::get().writes(1 as u64))
	}
	/// Storage:  (r: w:)
	/// Proof:  ()
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn release_stake(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  ``
		//  Estimated: ``
		// Minimum execution time: 136318_000 picoseconds.
		Weight::from_parts(143857000, )
			.saturating_add(DbWeight::get().reads(1 as u64))
			.saturating_add(DbWeight::get().writes(1 as u64))
	}
	/// Storage:  (r: w:)
	/// Proof:  ()
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn submit_heartbeat(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  ``
		//  Estimated: ``
		// Minimum execution time: 73626_000 picoseconds.
		Weight::from_parts(75855000, )
			.saturating_add(DbWeight::get().reads(1 as u64))
			.saturating_add(DbWeight::get().writes(1 as u64))
	}
	/// Storage:  (r: w:)
	/// Proof:  ()
	/// Storage: `NorthernSwarm::Tasks` (r:0 w:1)
	/// Proof: `NorthernSwarm::Tasks` (`max_values`: None, `max_size`: Some(684), added: 3159, mode: `MaxEncodedLen`)
	fn submit_task(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  ``
		//  Estimated: ``
		// Minimum execution time: 134182_000 picoseconds.
		Weight::from_parts(136872000, )
			.saturating_add(DbWeight::get().reads(0 as u64))
			.saturating_add(DbWeight::get().writes(1 as u64))
	}
	/// Storage:  (r: w:)
	/// Proof:  ()
	/// Storage: `NorthernSwarm::Executors` (r:1 w:0)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaims` (r:1 w:1)
	/// Proof: `NorthernSwarm::TaskClaims` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ClaimedTaskCount` (r:1 w:1)
	/// Proof: `NorthernSwarm::ClaimedTaskCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaimSlots` (r:1 w:1)
	/// Proof: `NorthernSwarm::TaskClaimSlots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::Tasks` (r:1 w:1)
	/// Proof: `NorthernSwarm::Tasks` (`max_values`: None, `max_size`: Some(684), added: 3159, mode: `MaxEncodedLen`)
	fn claim_task(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  ``
		//  Estimated: ``
		// Minimum execution time: 152677_000 picoseconds.
		Weight::from_parts(165549000, )
			.saturating_add(DbWeight::get().reads(5 as u64))
			.saturating_add(DbWeight::get().writes(4 as u64))
	}
	/// Storage:  (r: w:)
	/// Proof:  ()
	/// Storage: `NorthernSwarm::Executors` (r:1 w:0)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaims` (r:2 w:1)
	/// Proof: `NorthernSwarm::TaskClaims` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ResultCommits` (r:4 w:1)
	/// Proof: `NorthernSwarm::ResultCommits` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::Tasks` (r:1 w:1)
	/// Proof: `NorthernSwarm::Tasks` (`max_values`: None, `max_size`: Some(684), added: 3159, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ClaimedTaskCount` (r:1 w:1)
	/// Proof: `NorthernSwarm::ClaimedTaskCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaimSlots` (r:0 w:1)
	/// Proof: `NorthernSwarm::TaskClaimSlots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn submit_result(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  ``
		//  Estimated: ``
		// Minimum execution time: 446672_000 picoseconds.
		Weight::from_parts(462388000, )
			.saturating_add(DbWeight::get().reads(9 as u64))
			.saturating_add(DbWeight::get().writes(5 as u64))
	}
	/// Storage:  (r: w:)
	/// Proof:  ()
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn slash_executor(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  ``
		//  Estimated: ``
		// Minimum execution time: 169838_000 picoseconds.
		Weight::from_parts(190161000, )
			.saturating_add(DbWeight::get().reads(2 as u64))
			.saturating_add(DbWeight::get().writes(2 as u64))
	}
}
